// Generated by Haxe 4.0.0 (git build development @ be76e496e)
package haxe;

import haxe.root.*;

@SuppressWarnings(value={"rawtypes", "unchecked"})
public interface IMap<K, V> extends haxe.lang.IHxObject
{
}


