// Generated by Haxe 4.0.0 (git build development @ be76e496e)
package haxe;

import haxe.root.*;

@SuppressWarnings(value={"rawtypes", "unchecked"})
public class Log extends haxe.lang.HxObject
{
	static
	{
		//line 25 "C:\\Motion-Twin\\Haxe\\std\\java\\_std\\haxe\\Log.hx"
		haxe.Log.trace = ( (( haxe.Log_Anon_25__Fun.__hx_current != null )) ? (haxe.Log_Anon_25__Fun.__hx_current) : (haxe.Log_Anon_25__Fun.__hx_current = ((haxe.Log_Anon_25__Fun) (new haxe.Log_Anon_25__Fun()) )) );
	}
	
	public Log(haxe.lang.EmptyObject empty)
	{
	}
	
	
	public Log()
	{
		//line 24 "C:\\Motion-Twin\\Haxe\\std\\java\\_std\\haxe\\Log.hx"
		haxe.Log.__hx_ctor_haxe_Log(this);
	}
	
	
	protected static void __hx_ctor_haxe_Log(haxe.Log __hx_this)
	{
	}
	
	
	public static haxe.lang.Function trace;
	
}


