// Generated by Haxe 4.0.0 (git build development @ be76e496e)
package haxe;

import haxe.root.*;

@SuppressWarnings(value={"rawtypes", "unchecked"})
public class Serializer extends haxe.lang.HxObject
{
	static
	{
		//line 55 "C:\\Motion-Twin\\Haxe\\std\\haxe\\Serializer.hx"
		haxe.Serializer.USE_CACHE = false;
		//line 67 "C:\\Motion-Twin\\Haxe\\std\\haxe\\Serializer.hx"
		haxe.Serializer.USE_ENUM_INDEX = false;
		//line 69 "C:\\Motion-Twin\\Haxe\\std\\haxe\\Serializer.hx"
		haxe.Serializer.BASE64 = "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789%:";
		//line 70 "C:\\Motion-Twin\\Haxe\\std\\haxe\\Serializer.hx"
		haxe.Serializer.BASE64_CODES = null;
	}
	
	public Serializer(haxe.lang.EmptyObject empty)
	{
	}
	
	
	public Serializer()
	{
		//line 101 "C:\\Motion-Twin\\Haxe\\std\\haxe\\Serializer.hx"
		haxe.Serializer.__hx_ctor_haxe_Serializer(this);
	}
	
	
	protected static void __hx_ctor_haxe_Serializer(haxe.Serializer __hx_this)
	{
		//line 102 "C:\\Motion-Twin\\Haxe\\std\\haxe\\Serializer.hx"
		__hx_this.buf = new haxe.root.StringBuf();
		//line 103 "C:\\Motion-Twin\\Haxe\\std\\haxe\\Serializer.hx"
		__hx_this.cache = new haxe.root.Array();
		//line 104 "C:\\Motion-Twin\\Haxe\\std\\haxe\\Serializer.hx"
		__hx_this.useCache = haxe.Serializer.USE_CACHE;
		//line 105 "C:\\Motion-Twin\\Haxe\\std\\haxe\\Serializer.hx"
		__hx_this.useEnumIndex = haxe.Serializer.USE_ENUM_INDEX;
		//line 106 "C:\\Motion-Twin\\Haxe\\std\\haxe\\Serializer.hx"
		__hx_this.shash = new haxe.ds.StringMap<java.lang.Object>();
		//line 107 "C:\\Motion-Twin\\Haxe\\std\\haxe\\Serializer.hx"
		__hx_this.scount = 0;
	}
	
	
	public static boolean USE_CACHE;
	
	public static boolean USE_ENUM_INDEX;
	
	public static java.lang.String BASE64;
	
	public static java.lang.Object[] BASE64_CODES;
	
	public haxe.root.StringBuf buf;
	
	public haxe.root.Array cache;
	
	public haxe.ds.StringMap<java.lang.Object> shash;
	
	public int scount;
	
	public boolean useCache;
	
	public boolean useEnumIndex;
	
	@Override public java.lang.String toString()
	{
		//line 117 "C:\\Motion-Twin\\Haxe\\std\\haxe\\Serializer.hx"
		return this.buf.toString();
	}
	
	
	public void serializeString(java.lang.String s)
	{
		//line 154 "C:\\Motion-Twin\\Haxe\\std\\haxe\\Serializer.hx"
		java.lang.Object x = this.shash.get(s);
		//line 155 "C:\\Motion-Twin\\Haxe\\std\\haxe\\Serializer.hx"
		if (( ! (haxe.lang.Runtime.eq(x, null)) )) 
		{
			//line 156 "C:\\Motion-Twin\\Haxe\\std\\haxe\\Serializer.hx"
			this.buf.add(haxe.lang.Runtime.toString("R"));
			//line 157 "C:\\Motion-Twin\\Haxe\\std\\haxe\\Serializer.hx"
			this.buf.add(((java.lang.Object) (x) ));
			//line 158 "C:\\Motion-Twin\\Haxe\\std\\haxe\\Serializer.hx"
			return ;
		}
		
		//line 160 "C:\\Motion-Twin\\Haxe\\std\\haxe\\Serializer.hx"
		this.shash.set(s, this.scount++);
		//line 165 "C:\\Motion-Twin\\Haxe\\std\\haxe\\Serializer.hx"
		this.buf.add(haxe.lang.Runtime.toString("y"));
		//line 166 "C:\\Motion-Twin\\Haxe\\std\\haxe\\Serializer.hx"
		s = haxe.root.StringTools.urlEncode(s);
		//line 167 "C:\\Motion-Twin\\Haxe\\std\\haxe\\Serializer.hx"
		this.buf.add(((java.lang.Object) (s.length()) ));
		//line 168 "C:\\Motion-Twin\\Haxe\\std\\haxe\\Serializer.hx"
		this.buf.add(haxe.lang.Runtime.toString(":"));
		//line 169 "C:\\Motion-Twin\\Haxe\\std\\haxe\\Serializer.hx"
		this.buf.add(haxe.lang.Runtime.toString(s));
	}
	
	
	public boolean serializeRef(java.lang.Object v)
	{
		//line 176 "C:\\Motion-Twin\\Haxe\\std\\haxe\\Serializer.hx"
		{
			//line 176 "C:\\Motion-Twin\\Haxe\\std\\haxe\\Serializer.hx"
			int _g1 = 0;
			//line 176 "C:\\Motion-Twin\\Haxe\\std\\haxe\\Serializer.hx"
			int _g = this.cache.length;
			//line 176 "C:\\Motion-Twin\\Haxe\\std\\haxe\\Serializer.hx"
			while (( _g1 < _g ))
			{
				//line 176 "C:\\Motion-Twin\\Haxe\\std\\haxe\\Serializer.hx"
				int i = _g1++;
				//line 181 "C:\\Motion-Twin\\Haxe\\std\\haxe\\Serializer.hx"
				if (haxe.lang.Runtime.eq(this.cache.__get(i), v)) 
				{
					//line 183 "C:\\Motion-Twin\\Haxe\\std\\haxe\\Serializer.hx"
					this.buf.add(haxe.lang.Runtime.toString("r"));
					//line 184 "C:\\Motion-Twin\\Haxe\\std\\haxe\\Serializer.hx"
					this.buf.add(((java.lang.Object) (i) ));
					//line 185 "C:\\Motion-Twin\\Haxe\\std\\haxe\\Serializer.hx"
					return true;
				}
				
			}
			
		}
		
		//line 188 "C:\\Motion-Twin\\Haxe\\std\\haxe\\Serializer.hx"
		this.cache.push(v);
		//line 189 "C:\\Motion-Twin\\Haxe\\std\\haxe\\Serializer.hx"
		return false;
	}
	
	
	public void serializeFields(java.lang.Object v)
	{
		//line 210 "C:\\Motion-Twin\\Haxe\\std\\haxe\\Serializer.hx"
		{
			//line 210 "C:\\Motion-Twin\\Haxe\\std\\haxe\\Serializer.hx"
			int _g = 0;
			//line 210 "C:\\Motion-Twin\\Haxe\\std\\haxe\\Serializer.hx"
			haxe.root.Array<java.lang.String> _g1 = haxe.root.Reflect.fields(v);
			//line 210 "C:\\Motion-Twin\\Haxe\\std\\haxe\\Serializer.hx"
			while (( _g < _g1.length ))
			{
				//line 210 "C:\\Motion-Twin\\Haxe\\std\\haxe\\Serializer.hx"
				java.lang.String f = _g1.__get(_g);
				//line 210 "C:\\Motion-Twin\\Haxe\\std\\haxe\\Serializer.hx"
				 ++ _g;
				//line 211 "C:\\Motion-Twin\\Haxe\\std\\haxe\\Serializer.hx"
				this.serializeString(f);
				//line 212 "C:\\Motion-Twin\\Haxe\\std\\haxe\\Serializer.hx"
				this.serialize(haxe.root.Reflect.field(v, f));
			}
			
		}
		
		//line 214 "C:\\Motion-Twin\\Haxe\\std\\haxe\\Serializer.hx"
		this.buf.add(haxe.lang.Runtime.toString("g"));
	}
	
	
	public void serialize(java.lang.Object v)
	{
		//line 228 "C:\\Motion-Twin\\Haxe\\std\\haxe\\Serializer.hx"
		haxe.root.ValueType _g = haxe.root.Type.typeof(v);
		//line 228 "C:\\Motion-Twin\\Haxe\\std\\haxe\\Serializer.hx"
		switch (_g.index)
		{
			case 0:
			{
				//line 230 "C:\\Motion-Twin\\Haxe\\std\\haxe\\Serializer.hx"
				this.buf.add(haxe.lang.Runtime.toString("n"));
				//line 230 "C:\\Motion-Twin\\Haxe\\std\\haxe\\Serializer.hx"
				break;
			}
			
			
			case 1:
			{
				//line 232 "C:\\Motion-Twin\\Haxe\\std\\haxe\\Serializer.hx"
				int v1 = ((int) (haxe.lang.Runtime.toInt(v)) );
				//line 233 "C:\\Motion-Twin\\Haxe\\std\\haxe\\Serializer.hx"
				if (( v1 == 0 )) 
				{
					//line 234 "C:\\Motion-Twin\\Haxe\\std\\haxe\\Serializer.hx"
					this.buf.add(haxe.lang.Runtime.toString("z"));
					//line 235 "C:\\Motion-Twin\\Haxe\\std\\haxe\\Serializer.hx"
					return ;
				}
				
				//line 237 "C:\\Motion-Twin\\Haxe\\std\\haxe\\Serializer.hx"
				this.buf.add(haxe.lang.Runtime.toString("i"));
				//line 238 "C:\\Motion-Twin\\Haxe\\std\\haxe\\Serializer.hx"
				this.buf.add(((java.lang.Object) (v1) ));
				//line 231 "C:\\Motion-Twin\\Haxe\\std\\haxe\\Serializer.hx"
				break;
			}
			
			
			case 2:
			{
				//line 240 "C:\\Motion-Twin\\Haxe\\std\\haxe\\Serializer.hx"
				double v2 = ((double) (haxe.lang.Runtime.toDouble(v)) );
				//line 241 "C:\\Motion-Twin\\Haxe\\std\\haxe\\Serializer.hx"
				if (java.lang.Double.isNaN(v2)) 
				{
					//line 242 "C:\\Motion-Twin\\Haxe\\std\\haxe\\Serializer.hx"
					this.buf.add(haxe.lang.Runtime.toString("k"));
				}
				else
				{
					//line 243 "C:\\Motion-Twin\\Haxe\\std\\haxe\\Serializer.hx"
					if ( ! (haxe.lang.Runtime.isFinite(v2)) ) 
					{
						//line 244 "C:\\Motion-Twin\\Haxe\\std\\haxe\\Serializer.hx"
						this.buf.add(haxe.lang.Runtime.toString(( (( v2 < 0 )) ? ("m") : ("p") )));
					}
					else
					{
						//line 246 "C:\\Motion-Twin\\Haxe\\std\\haxe\\Serializer.hx"
						this.buf.add(haxe.lang.Runtime.toString("d"));
						//line 247 "C:\\Motion-Twin\\Haxe\\std\\haxe\\Serializer.hx"
						this.buf.add(((java.lang.Object) (v2) ));
					}
					
				}
				
				//line 239 "C:\\Motion-Twin\\Haxe\\std\\haxe\\Serializer.hx"
				break;
			}
			
			
			case 3:
			{
				//line 250 "C:\\Motion-Twin\\Haxe\\std\\haxe\\Serializer.hx"
				this.buf.add(haxe.lang.Runtime.toString(( (haxe.lang.Runtime.toBool(((java.lang.Boolean) ((v)) ))) ? ("t") : ("f") )));
				//line 250 "C:\\Motion-Twin\\Haxe\\std\\haxe\\Serializer.hx"
				break;
			}
			
			
			case 4:
			{
				//line 398 "C:\\Motion-Twin\\Haxe\\std\\haxe\\Serializer.hx"
				if (( v instanceof java.lang.Class )) 
				{
					//line 399 "C:\\Motion-Twin\\Haxe\\std\\haxe\\Serializer.hx"
					java.lang.String className = haxe.root.Type.getClassName(((java.lang.Class) (v) ));
					//line 405 "C:\\Motion-Twin\\Haxe\\std\\haxe\\Serializer.hx"
					this.buf.add(haxe.lang.Runtime.toString("A"));
					//line 406 "C:\\Motion-Twin\\Haxe\\std\\haxe\\Serializer.hx"
					this.serializeString(className);
				}
				else
				{
					//line 407 "C:\\Motion-Twin\\Haxe\\std\\haxe\\Serializer.hx"
					if (( v instanceof java.lang.Class )) 
					{
						//line 408 "C:\\Motion-Twin\\Haxe\\std\\haxe\\Serializer.hx"
						this.buf.add(haxe.lang.Runtime.toString("B"));
						//line 409 "C:\\Motion-Twin\\Haxe\\std\\haxe\\Serializer.hx"
						this.serializeString(haxe.root.Type.getEnumName(((java.lang.Class) (v) )));
					}
					else
					{
						//line 411 "C:\\Motion-Twin\\Haxe\\std\\haxe\\Serializer.hx"
						if (( this.useCache && this.serializeRef(v) )) 
						{
							//line 412 "C:\\Motion-Twin\\Haxe\\std\\haxe\\Serializer.hx"
							return ;
						}
						
						//line 413 "C:\\Motion-Twin\\Haxe\\std\\haxe\\Serializer.hx"
						this.buf.add(haxe.lang.Runtime.toString("o"));
						//line 414 "C:\\Motion-Twin\\Haxe\\std\\haxe\\Serializer.hx"
						this.serializeFields(v);
					}
					
				}
				
				//line 398 "C:\\Motion-Twin\\Haxe\\std\\haxe\\Serializer.hx"
				break;
			}
			
			
			case 5:
			{
				//line 528 "C:\\Motion-Twin\\Haxe\\std\\haxe\\Serializer.hx"
				throw haxe.lang.HaxeException.wrap("Cannot serialize function");
			}
			
			
			case 6:
			{
				//line 251 "C:\\Motion-Twin\\Haxe\\std\\haxe\\Serializer.hx"
				java.lang.Class c = ((java.lang.Class) (_g.params[0]) );
				//line 251 "C:\\Motion-Twin\\Haxe\\std\\haxe\\Serializer.hx"
				{
					//line 252 "C:\\Motion-Twin\\Haxe\\std\\haxe\\Serializer.hx"
					if (( ((java.lang.Object) (c) ) == ((java.lang.Object) (java.lang.String.class) ) )) 
					{
						//line 253 "C:\\Motion-Twin\\Haxe\\std\\haxe\\Serializer.hx"
						this.serializeString(haxe.lang.Runtime.toString(v));
						//line 254 "C:\\Motion-Twin\\Haxe\\std\\haxe\\Serializer.hx"
						return ;
					}
					
					//line 256 "C:\\Motion-Twin\\Haxe\\std\\haxe\\Serializer.hx"
					if (( this.useCache && this.serializeRef(v) )) 
					{
						//line 257 "C:\\Motion-Twin\\Haxe\\std\\haxe\\Serializer.hx"
						return ;
					}
					
					//line 258 "C:\\Motion-Twin\\Haxe\\std\\haxe\\Serializer.hx"
					{
						//line 258 "C:\\Motion-Twin\\Haxe\\std\\haxe\\Serializer.hx"
						java.lang.Class __temp_switch1 = (c);
						//line 259 "C:\\Motion-Twin\\Haxe\\std\\haxe\\Serializer.hx"
						if (( ((java.lang.Object) (__temp_switch1) ) == ((java.lang.Object) (haxe.root.Array.class) ) )) 
						{
							//line 260 "C:\\Motion-Twin\\Haxe\\std\\haxe\\Serializer.hx"
							int ucount = 0;
							//line 261 "C:\\Motion-Twin\\Haxe\\std\\haxe\\Serializer.hx"
							this.buf.add(haxe.lang.Runtime.toString("a"));
							//line 265 "C:\\Motion-Twin\\Haxe\\std\\haxe\\Serializer.hx"
							int l = ((int) (haxe.lang.Runtime.toInt(haxe.lang.Runtime.getField(v, "length", true))) );
							//line 266 "C:\\Motion-Twin\\Haxe\\std\\haxe\\Serializer.hx"
							{
								//line 266 "C:\\Motion-Twin\\Haxe\\std\\haxe\\Serializer.hx"
								int _g1 = 0;
								//line 266 "C:\\Motion-Twin\\Haxe\\std\\haxe\\Serializer.hx"
								while (( _g1 < l ))
								{
									//line 266 "C:\\Motion-Twin\\Haxe\\std\\haxe\\Serializer.hx"
									int i = _g1++;
									//line 267 "C:\\Motion-Twin\\Haxe\\std\\haxe\\Serializer.hx"
									if (( ((java.lang.Object) (haxe.lang.Runtime.callField(v, "__get", new java.lang.Object[]{i})) ) == null )) 
									{
										//line 268 "C:\\Motion-Twin\\Haxe\\std\\haxe\\Serializer.hx"
										 ++ ucount;
									}
									else
									{
										//line 270 "C:\\Motion-Twin\\Haxe\\std\\haxe\\Serializer.hx"
										if (( ucount > 0 )) 
										{
											//line 271 "C:\\Motion-Twin\\Haxe\\std\\haxe\\Serializer.hx"
											if (( ucount == 1 )) 
											{
												//line 272 "C:\\Motion-Twin\\Haxe\\std\\haxe\\Serializer.hx"
												this.buf.add(haxe.lang.Runtime.toString("n"));
											}
											else
											{
												//line 274 "C:\\Motion-Twin\\Haxe\\std\\haxe\\Serializer.hx"
												this.buf.add(haxe.lang.Runtime.toString("u"));
												//line 275 "C:\\Motion-Twin\\Haxe\\std\\haxe\\Serializer.hx"
												this.buf.add(((java.lang.Object) (ucount) ));
											}
											
											//line 277 "C:\\Motion-Twin\\Haxe\\std\\haxe\\Serializer.hx"
											ucount = 0;
										}
										
										//line 279 "C:\\Motion-Twin\\Haxe\\std\\haxe\\Serializer.hx"
										this.serialize(((java.lang.Object) (haxe.lang.Runtime.callField(v, "__get", new java.lang.Object[]{i})) ));
									}
									
								}
								
							}
							
							//line 282 "C:\\Motion-Twin\\Haxe\\std\\haxe\\Serializer.hx"
							if (( ucount > 0 )) 
							{
								//line 283 "C:\\Motion-Twin\\Haxe\\std\\haxe\\Serializer.hx"
								if (( ucount == 1 )) 
								{
									//line 284 "C:\\Motion-Twin\\Haxe\\std\\haxe\\Serializer.hx"
									this.buf.add(haxe.lang.Runtime.toString("n"));
								}
								else
								{
									//line 286 "C:\\Motion-Twin\\Haxe\\std\\haxe\\Serializer.hx"
									this.buf.add(haxe.lang.Runtime.toString("u"));
									//line 287 "C:\\Motion-Twin\\Haxe\\std\\haxe\\Serializer.hx"
									this.buf.add(((java.lang.Object) (ucount) ));
								}
								
							}
							
							//line 290 "C:\\Motion-Twin\\Haxe\\std\\haxe\\Serializer.hx"
							this.buf.add(haxe.lang.Runtime.toString("h"));
						}
						else
						{
							//line 297 "C:\\Motion-Twin\\Haxe\\std\\haxe\\Serializer.hx"
							if (( ((java.lang.Object) (__temp_switch1) ) == ((java.lang.Object) (haxe.root.Date.class) ) )) 
							{
								//line 298 "C:\\Motion-Twin\\Haxe\\std\\haxe\\Serializer.hx"
								haxe.root.Date d = ((haxe.root.Date) (v) );
								//line 299 "C:\\Motion-Twin\\Haxe\\std\\haxe\\Serializer.hx"
								this.buf.add(haxe.lang.Runtime.toString("v"));
								//line 300 "C:\\Motion-Twin\\Haxe\\std\\haxe\\Serializer.hx"
								this.buf.add(((double) (d.date.getTime()) ));
							}
							else
							{
								//line 291 "C:\\Motion-Twin\\Haxe\\std\\haxe\\Serializer.hx"
								if (( ((java.lang.Object) (__temp_switch1) ) == ((java.lang.Object) (haxe.root.List.class) ) )) 
								{
									//line 292 "C:\\Motion-Twin\\Haxe\\std\\haxe\\Serializer.hx"
									this.buf.add(haxe.lang.Runtime.toString("l"));
									//line 293 "C:\\Motion-Twin\\Haxe\\std\\haxe\\Serializer.hx"
									haxe.root.List v3 = ((haxe.root.List) (v) );
									//line 294 "C:\\Motion-Twin\\Haxe\\std\\haxe\\Serializer.hx"
									{
										//line 294 "C:\\Motion-Twin\\Haxe\\std\\haxe\\Serializer.hx"
										_List.ListNode _g_head = v3.h;
										//line 294 "C:\\Motion-Twin\\Haxe\\std\\haxe\\Serializer.hx"
										while (( _g_head != null ))
										{
											//line 294 "C:\\Motion-Twin\\Haxe\\std\\haxe\\Serializer.hx"
											java.lang.Object val = _g_head.item;
											//line 294 "C:\\Motion-Twin\\Haxe\\std\\haxe\\Serializer.hx"
											_g_head = _g_head.next;
											//line 295 "C:\\Motion-Twin\\Haxe\\std\\haxe\\Serializer.hx"
											this.serialize(val);
										}
										
									}
									
									//line 296 "C:\\Motion-Twin\\Haxe\\std\\haxe\\Serializer.hx"
									this.buf.add(haxe.lang.Runtime.toString("h"));
								}
								else
								{
									//line 309 "C:\\Motion-Twin\\Haxe\\std\\haxe\\Serializer.hx"
									if (( ((java.lang.Object) (__temp_switch1) ) == ((java.lang.Object) (haxe.ds.IntMap.class) ) )) 
									{
										//line 310 "C:\\Motion-Twin\\Haxe\\std\\haxe\\Serializer.hx"
										this.buf.add(haxe.lang.Runtime.toString("q"));
										//line 311 "C:\\Motion-Twin\\Haxe\\std\\haxe\\Serializer.hx"
										haxe.ds.IntMap v4 = ((haxe.ds.IntMap) (v) );
										//line 312 "C:\\Motion-Twin\\Haxe\\std\\haxe\\Serializer.hx"
										{
											//line 312 "C:\\Motion-Twin\\Haxe\\std\\haxe\\Serializer.hx"
											java.lang.Object k = ((java.lang.Object) (new haxe.ds._IntMap.IntMapKeyIterator(((haxe.ds.IntMap<java.lang.Object>) (v4) ))) );
											//line 312 "C:\\Motion-Twin\\Haxe\\std\\haxe\\Serializer.hx"
											while (haxe.lang.Runtime.toBool(((java.lang.Boolean) (haxe.lang.Runtime.callField(k, "hasNext", null)) )))
											{
												//line 312 "C:\\Motion-Twin\\Haxe\\std\\haxe\\Serializer.hx"
												int k1 = ((int) (haxe.lang.Runtime.toInt(haxe.lang.Runtime.callField(k, "next", null))) );
												//line 313 "C:\\Motion-Twin\\Haxe\\std\\haxe\\Serializer.hx"
												this.buf.add(haxe.lang.Runtime.toString(":"));
												//line 314 "C:\\Motion-Twin\\Haxe\\std\\haxe\\Serializer.hx"
												this.buf.add(((java.lang.Object) (k1) ));
												//line 315 "C:\\Motion-Twin\\Haxe\\std\\haxe\\Serializer.hx"
												this.serialize(v4.get(k1));
											}
											
										}
										
										//line 317 "C:\\Motion-Twin\\Haxe\\std\\haxe\\Serializer.hx"
										this.buf.add(haxe.lang.Runtime.toString("h"));
									}
									else
									{
										//line 318 "C:\\Motion-Twin\\Haxe\\std\\haxe\\Serializer.hx"
										if (( ((java.lang.Object) (__temp_switch1) ) == ((java.lang.Object) (haxe.ds.ObjectMap.class) ) )) 
										{
											//line 319 "C:\\Motion-Twin\\Haxe\\std\\haxe\\Serializer.hx"
											this.buf.add(haxe.lang.Runtime.toString("M"));
											//line 320 "C:\\Motion-Twin\\Haxe\\std\\haxe\\Serializer.hx"
											haxe.ds.ObjectMap v5 = ((haxe.ds.ObjectMap) (v) );
											//line 321 "C:\\Motion-Twin\\Haxe\\std\\haxe\\Serializer.hx"
											{
												//line 321 "C:\\Motion-Twin\\Haxe\\std\\haxe\\Serializer.hx"
												java.lang.Object k2 = v5.keys();
												//line 321 "C:\\Motion-Twin\\Haxe\\std\\haxe\\Serializer.hx"
												while (haxe.lang.Runtime.toBool(((java.lang.Boolean) (haxe.lang.Runtime.callField(k2, "hasNext", null)) )))
												{
													//line 321 "C:\\Motion-Twin\\Haxe\\std\\haxe\\Serializer.hx"
													java.lang.Object k3 = ((java.lang.Object) (haxe.lang.Runtime.callField(k2, "next", null)) );
													//line 328 "C:\\Motion-Twin\\Haxe\\std\\haxe\\Serializer.hx"
													this.serialize(k3);
													//line 330 "C:\\Motion-Twin\\Haxe\\std\\haxe\\Serializer.hx"
													this.serialize(v5.get(k3));
												}
												
											}
											
											//line 332 "C:\\Motion-Twin\\Haxe\\std\\haxe\\Serializer.hx"
											this.buf.add(haxe.lang.Runtime.toString("h"));
										}
										else
										{
											//line 301 "C:\\Motion-Twin\\Haxe\\std\\haxe\\Serializer.hx"
											if (( ((java.lang.Object) (__temp_switch1) ) == ((java.lang.Object) (haxe.ds.StringMap.class) ) )) 
											{
												//line 302 "C:\\Motion-Twin\\Haxe\\std\\haxe\\Serializer.hx"
												this.buf.add(haxe.lang.Runtime.toString("b"));
												//line 303 "C:\\Motion-Twin\\Haxe\\std\\haxe\\Serializer.hx"
												haxe.ds.StringMap v6 = ((haxe.ds.StringMap) (v) );
												//line 304 "C:\\Motion-Twin\\Haxe\\std\\haxe\\Serializer.hx"
												{
													//line 304 "C:\\Motion-Twin\\Haxe\\std\\haxe\\Serializer.hx"
													java.lang.Object k4 = ((java.lang.Object) (new haxe.ds._StringMap.StringMapKeyIterator(((haxe.ds.StringMap<java.lang.Object>) (v6) ))) );
													//line 304 "C:\\Motion-Twin\\Haxe\\std\\haxe\\Serializer.hx"
													while (haxe.lang.Runtime.toBool(((java.lang.Boolean) (haxe.lang.Runtime.callField(k4, "hasNext", null)) )))
													{
														//line 304 "C:\\Motion-Twin\\Haxe\\std\\haxe\\Serializer.hx"
														java.lang.String k5 = haxe.lang.Runtime.toString(haxe.lang.Runtime.callField(k4, "next", null));
														//line 305 "C:\\Motion-Twin\\Haxe\\std\\haxe\\Serializer.hx"
														this.serializeString(k5);
														//line 306 "C:\\Motion-Twin\\Haxe\\std\\haxe\\Serializer.hx"
														this.serialize(v6.get(k5));
													}
													
												}
												
												//line 308 "C:\\Motion-Twin\\Haxe\\std\\haxe\\Serializer.hx"
												this.buf.add(haxe.lang.Runtime.toString("h"));
											}
											else
											{
												//line 333 "C:\\Motion-Twin\\Haxe\\std\\haxe\\Serializer.hx"
												if (( ((java.lang.Object) (__temp_switch1) ) == ((java.lang.Object) (haxe.io.Bytes.class) ) )) 
												{
													//line 334 "C:\\Motion-Twin\\Haxe\\std\\haxe\\Serializer.hx"
													haxe.io.Bytes v7 = ((haxe.io.Bytes) (v) );
													//line 343 "C:\\Motion-Twin\\Haxe\\std\\haxe\\Serializer.hx"
													this.buf.add(haxe.lang.Runtime.toString("s"));
													//line 344 "C:\\Motion-Twin\\Haxe\\std\\haxe\\Serializer.hx"
													this.buf.add(((java.lang.Object) (((int) (java.lang.Math.ceil(( ((double) (( v7.length * 8 )) ) / 6 ))) )) ));
													//line 345 "C:\\Motion-Twin\\Haxe\\std\\haxe\\Serializer.hx"
													this.buf.add(haxe.lang.Runtime.toString(":"));
													//line 347 "C:\\Motion-Twin\\Haxe\\std\\haxe\\Serializer.hx"
													int i1 = 0;
													//line 348 "C:\\Motion-Twin\\Haxe\\std\\haxe\\Serializer.hx"
													int max = ( v7.length - 2 );
													//line 349 "C:\\Motion-Twin\\Haxe\\std\\haxe\\Serializer.hx"
													java.lang.Object[] b64 = haxe.Serializer.BASE64_CODES;
													//line 350 "C:\\Motion-Twin\\Haxe\\std\\haxe\\Serializer.hx"
													if (( b64 == null )) 
													{
														//line 351 "C:\\Motion-Twin\\Haxe\\std\\haxe\\Serializer.hx"
														java.lang.Object[] this1 = new java.lang.Object[haxe.Serializer.BASE64.length()];
														//line 351 "C:\\Motion-Twin\\Haxe\\std\\haxe\\Serializer.hx"
														b64 = ((java.lang.Object[]) (this1) );
														//line 352 "C:\\Motion-Twin\\Haxe\\std\\haxe\\Serializer.hx"
														{
															//line 352 "C:\\Motion-Twin\\Haxe\\std\\haxe\\Serializer.hx"
															int _g11 = 0;
															//line 352 "C:\\Motion-Twin\\Haxe\\std\\haxe\\Serializer.hx"
															int _g2 = haxe.Serializer.BASE64.length();
															//line 352 "C:\\Motion-Twin\\Haxe\\std\\haxe\\Serializer.hx"
															while (( _g11 < _g2 ))
															{
																//line 352 "C:\\Motion-Twin\\Haxe\\std\\haxe\\Serializer.hx"
																int i2 = _g11++;
																//line 353 "C:\\Motion-Twin\\Haxe\\std\\haxe\\Serializer.hx"
																((java.lang.Object[]) (b64) )[i2] = haxe.lang.StringExt.charCodeAt(haxe.Serializer.BASE64, i2);
															}
															
														}
														
														//line 354 "C:\\Motion-Twin\\Haxe\\std\\haxe\\Serializer.hx"
														haxe.Serializer.BASE64_CODES = b64;
													}
													
													//line 356 "C:\\Motion-Twin\\Haxe\\std\\haxe\\Serializer.hx"
													while (( i1 < max ))
													{
														//line 357 "C:\\Motion-Twin\\Haxe\\std\\haxe\\Serializer.hx"
														int b1 = ( v7.b[i1++] & 255 );
														//line 358 "C:\\Motion-Twin\\Haxe\\std\\haxe\\Serializer.hx"
														int b2 = ( v7.b[i1++] & 255 );
														//line 359 "C:\\Motion-Twin\\Haxe\\std\\haxe\\Serializer.hx"
														int b3 = ( v7.b[i1++] & 255 );
														//line 361 "C:\\Motion-Twin\\Haxe\\std\\haxe\\Serializer.hx"
														this.buf.addChar(((int) (haxe.lang.Runtime.toInt(((java.lang.Object) (((java.lang.Object[]) (b64) )[( b1 >> 2 )]) ))) ));
														//line 362 "C:\\Motion-Twin\\Haxe\\std\\haxe\\Serializer.hx"
														this.buf.addChar(((int) (haxe.lang.Runtime.toInt(((java.lang.Object) (((java.lang.Object[]) (b64) )[( (( ( b1 << 4 ) | ( b2 >> 4 ) )) & 63 )]) ))) ));
														//line 363 "C:\\Motion-Twin\\Haxe\\std\\haxe\\Serializer.hx"
														this.buf.addChar(((int) (haxe.lang.Runtime.toInt(((java.lang.Object) (((java.lang.Object[]) (b64) )[( (( ( b2 << 2 ) | ( b3 >> 6 ) )) & 63 )]) ))) ));
														//line 364 "C:\\Motion-Twin\\Haxe\\std\\haxe\\Serializer.hx"
														this.buf.addChar(((int) (haxe.lang.Runtime.toInt(((java.lang.Object) (((java.lang.Object[]) (b64) )[( b3 & 63 )]) ))) ));
													}
													
													//line 366 "C:\\Motion-Twin\\Haxe\\std\\haxe\\Serializer.hx"
													if (( i1 == max )) 
													{
														//line 367 "C:\\Motion-Twin\\Haxe\\std\\haxe\\Serializer.hx"
														int b11 = ( v7.b[i1++] & 255 );
														//line 368 "C:\\Motion-Twin\\Haxe\\std\\haxe\\Serializer.hx"
														int b21 = ( v7.b[i1++] & 255 );
														//line 369 "C:\\Motion-Twin\\Haxe\\std\\haxe\\Serializer.hx"
														this.buf.addChar(((int) (haxe.lang.Runtime.toInt(((java.lang.Object) (((java.lang.Object[]) (b64) )[( b11 >> 2 )]) ))) ));
														//line 370 "C:\\Motion-Twin\\Haxe\\std\\haxe\\Serializer.hx"
														this.buf.addChar(((int) (haxe.lang.Runtime.toInt(((java.lang.Object) (((java.lang.Object[]) (b64) )[( (( ( b11 << 4 ) | ( b21 >> 4 ) )) & 63 )]) ))) ));
														//line 371 "C:\\Motion-Twin\\Haxe\\std\\haxe\\Serializer.hx"
														this.buf.addChar(((int) (haxe.lang.Runtime.toInt(((java.lang.Object) (((java.lang.Object[]) (b64) )[( ( b21 << 2 ) & 63 )]) ))) ));
													}
													else
													{
														//line 372 "C:\\Motion-Twin\\Haxe\\std\\haxe\\Serializer.hx"
														if (( i1 == ( max + 1 ) )) 
														{
															//line 373 "C:\\Motion-Twin\\Haxe\\std\\haxe\\Serializer.hx"
															int b12 = ( v7.b[i1++] & 255 );
															//line 374 "C:\\Motion-Twin\\Haxe\\std\\haxe\\Serializer.hx"
															this.buf.addChar(((int) (haxe.lang.Runtime.toInt(((java.lang.Object) (((java.lang.Object[]) (b64) )[( b12 >> 2 )]) ))) ));
															//line 375 "C:\\Motion-Twin\\Haxe\\std\\haxe\\Serializer.hx"
															this.buf.addChar(((int) (haxe.lang.Runtime.toInt(((java.lang.Object) (((java.lang.Object[]) (b64) )[( ( b12 << 4 ) & 63 )]) ))) ));
														}
														
													}
													
												}
												else
												{
													//line 379 "C:\\Motion-Twin\\Haxe\\std\\haxe\\Serializer.hx"
													if (this.useCache) 
													{
														//line 379 "C:\\Motion-Twin\\Haxe\\std\\haxe\\Serializer.hx"
														this.cache.pop();
													}
													
													//line 380 "C:\\Motion-Twin\\Haxe\\std\\haxe\\Serializer.hx"
													if (haxe.root.Reflect.hasField(v, "hxSerialize")) 
													{
														//line 381 "C:\\Motion-Twin\\Haxe\\std\\haxe\\Serializer.hx"
														this.buf.add(haxe.lang.Runtime.toString("C"));
														//line 382 "C:\\Motion-Twin\\Haxe\\std\\haxe\\Serializer.hx"
														this.serializeString(haxe.root.Type.getClassName(c));
														//line 383 "C:\\Motion-Twin\\Haxe\\std\\haxe\\Serializer.hx"
														if (this.useCache) 
														{
															//line 383 "C:\\Motion-Twin\\Haxe\\std\\haxe\\Serializer.hx"
															this.cache.push(v);
														}
														
														//line 384 "C:\\Motion-Twin\\Haxe\\std\\haxe\\Serializer.hx"
														haxe.lang.Runtime.callField(v, "hxSerialize", new java.lang.Object[]{this});
														//line 385 "C:\\Motion-Twin\\Haxe\\std\\haxe\\Serializer.hx"
														this.buf.add(haxe.lang.Runtime.toString("g"));
													}
													else
													{
														//line 387 "C:\\Motion-Twin\\Haxe\\std\\haxe\\Serializer.hx"
														this.buf.add(haxe.lang.Runtime.toString("c"));
														//line 388 "C:\\Motion-Twin\\Haxe\\std\\haxe\\Serializer.hx"
														this.serializeString(haxe.root.Type.getClassName(c));
														//line 389 "C:\\Motion-Twin\\Haxe\\std\\haxe\\Serializer.hx"
														if (this.useCache) 
														{
															//line 389 "C:\\Motion-Twin\\Haxe\\std\\haxe\\Serializer.hx"
															this.cache.push(v);
														}
														
														//line 393 "C:\\Motion-Twin\\Haxe\\std\\haxe\\Serializer.hx"
														this.serializeFields(v);
													}
													
												}
												
											}
											
										}
										
									}
									
								}
								
							}
							
						}
						
					}
					
				}
				
				//line 251 "C:\\Motion-Twin\\Haxe\\std\\haxe\\Serializer.hx"
				break;
			}
			
			
			case 7:
			{
				//line 416 "C:\\Motion-Twin\\Haxe\\std\\haxe\\Serializer.hx"
				java.lang.Class e = ((java.lang.Class) (_g.params[0]) );
				//line 416 "C:\\Motion-Twin\\Haxe\\std\\haxe\\Serializer.hx"
				{
					//line 417 "C:\\Motion-Twin\\Haxe\\std\\haxe\\Serializer.hx"
					if (this.useCache) 
					{
						//line 418 "C:\\Motion-Twin\\Haxe\\std\\haxe\\Serializer.hx"
						if (this.serializeRef(v)) 
						{
							//line 419 "C:\\Motion-Twin\\Haxe\\std\\haxe\\Serializer.hx"
							return ;
						}
						
						//line 420 "C:\\Motion-Twin\\Haxe\\std\\haxe\\Serializer.hx"
						this.cache.pop();
					}
					
					//line 422 "C:\\Motion-Twin\\Haxe\\std\\haxe\\Serializer.hx"
					this.buf.add(haxe.lang.Runtime.toString(( (this.useEnumIndex) ? ("j") : ("w") )));
					//line 423 "C:\\Motion-Twin\\Haxe\\std\\haxe\\Serializer.hx"
					this.serializeString(haxe.root.Type.getEnumName(e));
					//line 488 "C:\\Motion-Twin\\Haxe\\std\\haxe\\Serializer.hx"
					if (this.useEnumIndex) 
					{
						//line 489 "C:\\Motion-Twin\\Haxe\\std\\haxe\\Serializer.hx"
						this.buf.add(haxe.lang.Runtime.toString(":"));
						//line 490 "C:\\Motion-Twin\\Haxe\\std\\haxe\\Serializer.hx"
						this.buf.add(((java.lang.Object) (haxe.root.Type.enumIndex(v)) ));
					}
					else
					{
						//line 492 "C:\\Motion-Twin\\Haxe\\std\\haxe\\Serializer.hx"
						this.serializeString(haxe.root.Type.enumConstructor(v));
					}
					
					//line 493 "C:\\Motion-Twin\\Haxe\\std\\haxe\\Serializer.hx"
					this.buf.add(haxe.lang.Runtime.toString(":"));
					//line 494 "C:\\Motion-Twin\\Haxe\\std\\haxe\\Serializer.hx"
					haxe.root.Array arr = haxe.root.Type.enumParameters(v);
					//line 495 "C:\\Motion-Twin\\Haxe\\std\\haxe\\Serializer.hx"
					if (( arr != null )) 
					{
						//line 497 "C:\\Motion-Twin\\Haxe\\std\\haxe\\Serializer.hx"
						this.buf.add(((java.lang.Object) (arr.length) ));
						//line 498 "C:\\Motion-Twin\\Haxe\\std\\haxe\\Serializer.hx"
						{
							//line 498 "C:\\Motion-Twin\\Haxe\\std\\haxe\\Serializer.hx"
							int _g3 = 0;
							//line 498 "C:\\Motion-Twin\\Haxe\\std\\haxe\\Serializer.hx"
							while (( _g3 < arr.length ))
							{
								//line 498 "C:\\Motion-Twin\\Haxe\\std\\haxe\\Serializer.hx"
								java.lang.Object v8 = arr.__get(_g3);
								//line 498 "C:\\Motion-Twin\\Haxe\\std\\haxe\\Serializer.hx"
								 ++ _g3;
								//line 499 "C:\\Motion-Twin\\Haxe\\std\\haxe\\Serializer.hx"
								this.serialize(v8);
							}
							
						}
						
					}
					else
					{
						//line 501 "C:\\Motion-Twin\\Haxe\\std\\haxe\\Serializer.hx"
						this.buf.add(haxe.lang.Runtime.toString("0"));
					}
					
					//line 526 "C:\\Motion-Twin\\Haxe\\std\\haxe\\Serializer.hx"
					if (this.useCache) 
					{
						//line 526 "C:\\Motion-Twin\\Haxe\\std\\haxe\\Serializer.hx"
						this.cache.push(v);
					}
					
				}
				
				//line 416 "C:\\Motion-Twin\\Haxe\\std\\haxe\\Serializer.hx"
				break;
			}
			
			
			default:
			{
				//line 537 "C:\\Motion-Twin\\Haxe\\std\\haxe\\Serializer.hx"
				throw haxe.lang.HaxeException.wrap(( "Cannot serialize " + haxe.root.Std.string(v) ));
			}
			
		}
		
	}
	
	
	public void serializeException(java.lang.Object e)
	{
		//line 544 "C:\\Motion-Twin\\Haxe\\std\\haxe\\Serializer.hx"
		this.buf.add(haxe.lang.Runtime.toString("x"));
		//line 556 "C:\\Motion-Twin\\Haxe\\std\\haxe\\Serializer.hx"
		this.serialize(e);
	}
	
	
	@Override public double __hx_setField_f(java.lang.String field, double value, boolean handleProperties)
	{
		//line 42 "C:\\Motion-Twin\\Haxe\\std\\haxe\\Serializer.hx"
		{
			//line 42 "C:\\Motion-Twin\\Haxe\\std\\haxe\\Serializer.hx"
			boolean __temp_executeDef1 = true;
			//line 42 "C:\\Motion-Twin\\Haxe\\std\\haxe\\Serializer.hx"
			switch (field.hashCode())
			{
				case -907763588:
				{
					//line 42 "C:\\Motion-Twin\\Haxe\\std\\haxe\\Serializer.hx"
					if (field.equals("scount")) 
					{
						//line 42 "C:\\Motion-Twin\\Haxe\\std\\haxe\\Serializer.hx"
						__temp_executeDef1 = false;
						//line 42 "C:\\Motion-Twin\\Haxe\\std\\haxe\\Serializer.hx"
						this.scount = ((int) (value) );
						//line 42 "C:\\Motion-Twin\\Haxe\\std\\haxe\\Serializer.hx"
						return value;
					}
					
					//line 42 "C:\\Motion-Twin\\Haxe\\std\\haxe\\Serializer.hx"
					break;
				}
				
				
			}
			
			//line 42 "C:\\Motion-Twin\\Haxe\\std\\haxe\\Serializer.hx"
			if (__temp_executeDef1) 
			{
				//line 42 "C:\\Motion-Twin\\Haxe\\std\\haxe\\Serializer.hx"
				return super.__hx_setField_f(field, value, handleProperties);
			}
			else
			{
				//line 42 "C:\\Motion-Twin\\Haxe\\std\\haxe\\Serializer.hx"
				throw null;
			}
			
		}
		
	}
	
	
	@Override public java.lang.Object __hx_setField(java.lang.String field, java.lang.Object value, boolean handleProperties)
	{
		//line 42 "C:\\Motion-Twin\\Haxe\\std\\haxe\\Serializer.hx"
		{
			//line 42 "C:\\Motion-Twin\\Haxe\\std\\haxe\\Serializer.hx"
			boolean __temp_executeDef1 = true;
			//line 42 "C:\\Motion-Twin\\Haxe\\std\\haxe\\Serializer.hx"
			switch (field.hashCode())
			{
				case 1284193930:
				{
					//line 42 "C:\\Motion-Twin\\Haxe\\std\\haxe\\Serializer.hx"
					if (field.equals("useEnumIndex")) 
					{
						//line 42 "C:\\Motion-Twin\\Haxe\\std\\haxe\\Serializer.hx"
						__temp_executeDef1 = false;
						//line 42 "C:\\Motion-Twin\\Haxe\\std\\haxe\\Serializer.hx"
						this.useEnumIndex = haxe.lang.Runtime.toBool(((java.lang.Boolean) (value) ));
						//line 42 "C:\\Motion-Twin\\Haxe\\std\\haxe\\Serializer.hx"
						return value;
					}
					
					//line 42 "C:\\Motion-Twin\\Haxe\\std\\haxe\\Serializer.hx"
					break;
				}
				
				
				case 97907:
				{
					//line 42 "C:\\Motion-Twin\\Haxe\\std\\haxe\\Serializer.hx"
					if (field.equals("buf")) 
					{
						//line 42 "C:\\Motion-Twin\\Haxe\\std\\haxe\\Serializer.hx"
						__temp_executeDef1 = false;
						//line 42 "C:\\Motion-Twin\\Haxe\\std\\haxe\\Serializer.hx"
						this.buf = ((haxe.root.StringBuf) (value) );
						//line 42 "C:\\Motion-Twin\\Haxe\\std\\haxe\\Serializer.hx"
						return value;
					}
					
					//line 42 "C:\\Motion-Twin\\Haxe\\std\\haxe\\Serializer.hx"
					break;
				}
				
				
				case -309504453:
				{
					//line 42 "C:\\Motion-Twin\\Haxe\\std\\haxe\\Serializer.hx"
					if (field.equals("useCache")) 
					{
						//line 42 "C:\\Motion-Twin\\Haxe\\std\\haxe\\Serializer.hx"
						__temp_executeDef1 = false;
						//line 42 "C:\\Motion-Twin\\Haxe\\std\\haxe\\Serializer.hx"
						this.useCache = haxe.lang.Runtime.toBool(((java.lang.Boolean) (value) ));
						//line 42 "C:\\Motion-Twin\\Haxe\\std\\haxe\\Serializer.hx"
						return value;
					}
					
					//line 42 "C:\\Motion-Twin\\Haxe\\std\\haxe\\Serializer.hx"
					break;
				}
				
				
				case 94416770:
				{
					//line 42 "C:\\Motion-Twin\\Haxe\\std\\haxe\\Serializer.hx"
					if (field.equals("cache")) 
					{
						//line 42 "C:\\Motion-Twin\\Haxe\\std\\haxe\\Serializer.hx"
						__temp_executeDef1 = false;
						//line 42 "C:\\Motion-Twin\\Haxe\\std\\haxe\\Serializer.hx"
						this.cache = ((haxe.root.Array) (value) );
						//line 42 "C:\\Motion-Twin\\Haxe\\std\\haxe\\Serializer.hx"
						return value;
					}
					
					//line 42 "C:\\Motion-Twin\\Haxe\\std\\haxe\\Serializer.hx"
					break;
				}
				
				
				case -907763588:
				{
					//line 42 "C:\\Motion-Twin\\Haxe\\std\\haxe\\Serializer.hx"
					if (field.equals("scount")) 
					{
						//line 42 "C:\\Motion-Twin\\Haxe\\std\\haxe\\Serializer.hx"
						__temp_executeDef1 = false;
						//line 42 "C:\\Motion-Twin\\Haxe\\std\\haxe\\Serializer.hx"
						this.scount = ((int) (haxe.lang.Runtime.toInt(value)) );
						//line 42 "C:\\Motion-Twin\\Haxe\\std\\haxe\\Serializer.hx"
						return value;
					}
					
					//line 42 "C:\\Motion-Twin\\Haxe\\std\\haxe\\Serializer.hx"
					break;
				}
				
				
				case 109400065:
				{
					//line 42 "C:\\Motion-Twin\\Haxe\\std\\haxe\\Serializer.hx"
					if (field.equals("shash")) 
					{
						//line 42 "C:\\Motion-Twin\\Haxe\\std\\haxe\\Serializer.hx"
						__temp_executeDef1 = false;
						//line 42 "C:\\Motion-Twin\\Haxe\\std\\haxe\\Serializer.hx"
						this.shash = ((haxe.ds.StringMap<java.lang.Object>) (value) );
						//line 42 "C:\\Motion-Twin\\Haxe\\std\\haxe\\Serializer.hx"
						return value;
					}
					
					//line 42 "C:\\Motion-Twin\\Haxe\\std\\haxe\\Serializer.hx"
					break;
				}
				
				
			}
			
			//line 42 "C:\\Motion-Twin\\Haxe\\std\\haxe\\Serializer.hx"
			if (__temp_executeDef1) 
			{
				//line 42 "C:\\Motion-Twin\\Haxe\\std\\haxe\\Serializer.hx"
				return super.__hx_setField(field, value, handleProperties);
			}
			else
			{
				//line 42 "C:\\Motion-Twin\\Haxe\\std\\haxe\\Serializer.hx"
				throw null;
			}
			
		}
		
	}
	
	
	@Override public java.lang.Object __hx_getField(java.lang.String field, boolean throwErrors, boolean isCheck, boolean handleProperties)
	{
		//line 42 "C:\\Motion-Twin\\Haxe\\std\\haxe\\Serializer.hx"
		{
			//line 42 "C:\\Motion-Twin\\Haxe\\std\\haxe\\Serializer.hx"
			boolean __temp_executeDef1 = true;
			//line 42 "C:\\Motion-Twin\\Haxe\\std\\haxe\\Serializer.hx"
			switch (field.hashCode())
			{
				case -261733041:
				{
					//line 42 "C:\\Motion-Twin\\Haxe\\std\\haxe\\Serializer.hx"
					if (field.equals("serializeException")) 
					{
						//line 42 "C:\\Motion-Twin\\Haxe\\std\\haxe\\Serializer.hx"
						__temp_executeDef1 = false;
						//line 42 "C:\\Motion-Twin\\Haxe\\std\\haxe\\Serializer.hx"
						return ((haxe.lang.Function) (new haxe.lang.Closure(this, "serializeException")) );
					}
					
					//line 42 "C:\\Motion-Twin\\Haxe\\std\\haxe\\Serializer.hx"
					break;
				}
				
				
				case 97907:
				{
					//line 42 "C:\\Motion-Twin\\Haxe\\std\\haxe\\Serializer.hx"
					if (field.equals("buf")) 
					{
						//line 42 "C:\\Motion-Twin\\Haxe\\std\\haxe\\Serializer.hx"
						__temp_executeDef1 = false;
						//line 42 "C:\\Motion-Twin\\Haxe\\std\\haxe\\Serializer.hx"
						return this.buf;
					}
					
					//line 42 "C:\\Motion-Twin\\Haxe\\std\\haxe\\Serializer.hx"
					break;
				}
				
				
				case -573479200:
				{
					//line 42 "C:\\Motion-Twin\\Haxe\\std\\haxe\\Serializer.hx"
					if (field.equals("serialize")) 
					{
						//line 42 "C:\\Motion-Twin\\Haxe\\std\\haxe\\Serializer.hx"
						__temp_executeDef1 = false;
						//line 42 "C:\\Motion-Twin\\Haxe\\std\\haxe\\Serializer.hx"
						return ((haxe.lang.Function) (new haxe.lang.Closure(this, "serialize")) );
					}
					
					//line 42 "C:\\Motion-Twin\\Haxe\\std\\haxe\\Serializer.hx"
					break;
				}
				
				
				case 94416770:
				{
					//line 42 "C:\\Motion-Twin\\Haxe\\std\\haxe\\Serializer.hx"
					if (field.equals("cache")) 
					{
						//line 42 "C:\\Motion-Twin\\Haxe\\std\\haxe\\Serializer.hx"
						__temp_executeDef1 = false;
						//line 42 "C:\\Motion-Twin\\Haxe\\std\\haxe\\Serializer.hx"
						return this.cache;
					}
					
					//line 42 "C:\\Motion-Twin\\Haxe\\std\\haxe\\Serializer.hx"
					break;
				}
				
				
				case -7657031:
				{
					//line 42 "C:\\Motion-Twin\\Haxe\\std\\haxe\\Serializer.hx"
					if (field.equals("serializeFields")) 
					{
						//line 42 "C:\\Motion-Twin\\Haxe\\std\\haxe\\Serializer.hx"
						__temp_executeDef1 = false;
						//line 42 "C:\\Motion-Twin\\Haxe\\std\\haxe\\Serializer.hx"
						return ((haxe.lang.Function) (new haxe.lang.Closure(this, "serializeFields")) );
					}
					
					//line 42 "C:\\Motion-Twin\\Haxe\\std\\haxe\\Serializer.hx"
					break;
				}
				
				
				case 109400065:
				{
					//line 42 "C:\\Motion-Twin\\Haxe\\std\\haxe\\Serializer.hx"
					if (field.equals("shash")) 
					{
						//line 42 "C:\\Motion-Twin\\Haxe\\std\\haxe\\Serializer.hx"
						__temp_executeDef1 = false;
						//line 42 "C:\\Motion-Twin\\Haxe\\std\\haxe\\Serializer.hx"
						return this.shash;
					}
					
					//line 42 "C:\\Motion-Twin\\Haxe\\std\\haxe\\Serializer.hx"
					break;
				}
				
				
				case 861138323:
				{
					//line 42 "C:\\Motion-Twin\\Haxe\\std\\haxe\\Serializer.hx"
					if (field.equals("serializeRef")) 
					{
						//line 42 "C:\\Motion-Twin\\Haxe\\std\\haxe\\Serializer.hx"
						__temp_executeDef1 = false;
						//line 42 "C:\\Motion-Twin\\Haxe\\std\\haxe\\Serializer.hx"
						return ((haxe.lang.Function) (new haxe.lang.Closure(this, "serializeRef")) );
					}
					
					//line 42 "C:\\Motion-Twin\\Haxe\\std\\haxe\\Serializer.hx"
					break;
				}
				
				
				case -907763588:
				{
					//line 42 "C:\\Motion-Twin\\Haxe\\std\\haxe\\Serializer.hx"
					if (field.equals("scount")) 
					{
						//line 42 "C:\\Motion-Twin\\Haxe\\std\\haxe\\Serializer.hx"
						__temp_executeDef1 = false;
						//line 42 "C:\\Motion-Twin\\Haxe\\std\\haxe\\Serializer.hx"
						return this.scount;
					}
					
					//line 42 "C:\\Motion-Twin\\Haxe\\std\\haxe\\Serializer.hx"
					break;
				}
				
				
				case 375065361:
				{
					//line 42 "C:\\Motion-Twin\\Haxe\\std\\haxe\\Serializer.hx"
					if (field.equals("serializeString")) 
					{
						//line 42 "C:\\Motion-Twin\\Haxe\\std\\haxe\\Serializer.hx"
						__temp_executeDef1 = false;
						//line 42 "C:\\Motion-Twin\\Haxe\\std\\haxe\\Serializer.hx"
						return ((haxe.lang.Function) (new haxe.lang.Closure(this, "serializeString")) );
					}
					
					//line 42 "C:\\Motion-Twin\\Haxe\\std\\haxe\\Serializer.hx"
					break;
				}
				
				
				case -309504453:
				{
					//line 42 "C:\\Motion-Twin\\Haxe\\std\\haxe\\Serializer.hx"
					if (field.equals("useCache")) 
					{
						//line 42 "C:\\Motion-Twin\\Haxe\\std\\haxe\\Serializer.hx"
						__temp_executeDef1 = false;
						//line 42 "C:\\Motion-Twin\\Haxe\\std\\haxe\\Serializer.hx"
						return this.useCache;
					}
					
					//line 42 "C:\\Motion-Twin\\Haxe\\std\\haxe\\Serializer.hx"
					break;
				}
				
				
				case -1776922004:
				{
					//line 42 "C:\\Motion-Twin\\Haxe\\std\\haxe\\Serializer.hx"
					if (field.equals("toString")) 
					{
						//line 42 "C:\\Motion-Twin\\Haxe\\std\\haxe\\Serializer.hx"
						__temp_executeDef1 = false;
						//line 42 "C:\\Motion-Twin\\Haxe\\std\\haxe\\Serializer.hx"
						return ((haxe.lang.Function) (new haxe.lang.Closure(this, "toString")) );
					}
					
					//line 42 "C:\\Motion-Twin\\Haxe\\std\\haxe\\Serializer.hx"
					break;
				}
				
				
				case 1284193930:
				{
					//line 42 "C:\\Motion-Twin\\Haxe\\std\\haxe\\Serializer.hx"
					if (field.equals("useEnumIndex")) 
					{
						//line 42 "C:\\Motion-Twin\\Haxe\\std\\haxe\\Serializer.hx"
						__temp_executeDef1 = false;
						//line 42 "C:\\Motion-Twin\\Haxe\\std\\haxe\\Serializer.hx"
						return this.useEnumIndex;
					}
					
					//line 42 "C:\\Motion-Twin\\Haxe\\std\\haxe\\Serializer.hx"
					break;
				}
				
				
			}
			
			//line 42 "C:\\Motion-Twin\\Haxe\\std\\haxe\\Serializer.hx"
			if (__temp_executeDef1) 
			{
				//line 42 "C:\\Motion-Twin\\Haxe\\std\\haxe\\Serializer.hx"
				return super.__hx_getField(field, throwErrors, isCheck, handleProperties);
			}
			else
			{
				//line 42 "C:\\Motion-Twin\\Haxe\\std\\haxe\\Serializer.hx"
				throw null;
			}
			
		}
		
	}
	
	
	@Override public double __hx_getField_f(java.lang.String field, boolean throwErrors, boolean handleProperties)
	{
		//line 42 "C:\\Motion-Twin\\Haxe\\std\\haxe\\Serializer.hx"
		{
			//line 42 "C:\\Motion-Twin\\Haxe\\std\\haxe\\Serializer.hx"
			boolean __temp_executeDef1 = true;
			//line 42 "C:\\Motion-Twin\\Haxe\\std\\haxe\\Serializer.hx"
			switch (field.hashCode())
			{
				case -907763588:
				{
					//line 42 "C:\\Motion-Twin\\Haxe\\std\\haxe\\Serializer.hx"
					if (field.equals("scount")) 
					{
						//line 42 "C:\\Motion-Twin\\Haxe\\std\\haxe\\Serializer.hx"
						__temp_executeDef1 = false;
						//line 42 "C:\\Motion-Twin\\Haxe\\std\\haxe\\Serializer.hx"
						return ((double) (this.scount) );
					}
					
					//line 42 "C:\\Motion-Twin\\Haxe\\std\\haxe\\Serializer.hx"
					break;
				}
				
				
			}
			
			//line 42 "C:\\Motion-Twin\\Haxe\\std\\haxe\\Serializer.hx"
			if (__temp_executeDef1) 
			{
				//line 42 "C:\\Motion-Twin\\Haxe\\std\\haxe\\Serializer.hx"
				return super.__hx_getField_f(field, throwErrors, handleProperties);
			}
			else
			{
				//line 42 "C:\\Motion-Twin\\Haxe\\std\\haxe\\Serializer.hx"
				throw null;
			}
			
		}
		
	}
	
	
	@Override public java.lang.Object __hx_invokeField(java.lang.String field, java.lang.Object[] dynargs)
	{
		//line 42 "C:\\Motion-Twin\\Haxe\\std\\haxe\\Serializer.hx"
		{
			//line 42 "C:\\Motion-Twin\\Haxe\\std\\haxe\\Serializer.hx"
			boolean __temp_executeDef1 = true;
			//line 42 "C:\\Motion-Twin\\Haxe\\std\\haxe\\Serializer.hx"
			switch (field.hashCode())
			{
				case -261733041:
				{
					//line 42 "C:\\Motion-Twin\\Haxe\\std\\haxe\\Serializer.hx"
					if (field.equals("serializeException")) 
					{
						//line 42 "C:\\Motion-Twin\\Haxe\\std\\haxe\\Serializer.hx"
						__temp_executeDef1 = false;
						//line 42 "C:\\Motion-Twin\\Haxe\\std\\haxe\\Serializer.hx"
						this.serializeException(dynargs[0]);
					}
					
					//line 42 "C:\\Motion-Twin\\Haxe\\std\\haxe\\Serializer.hx"
					break;
				}
				
				
				case -1776922004:
				{
					//line 42 "C:\\Motion-Twin\\Haxe\\std\\haxe\\Serializer.hx"
					if (field.equals("toString")) 
					{
						//line 42 "C:\\Motion-Twin\\Haxe\\std\\haxe\\Serializer.hx"
						__temp_executeDef1 = false;
						//line 42 "C:\\Motion-Twin\\Haxe\\std\\haxe\\Serializer.hx"
						return this.toString();
					}
					
					//line 42 "C:\\Motion-Twin\\Haxe\\std\\haxe\\Serializer.hx"
					break;
				}
				
				
				case -573479200:
				{
					//line 42 "C:\\Motion-Twin\\Haxe\\std\\haxe\\Serializer.hx"
					if (field.equals("serialize")) 
					{
						//line 42 "C:\\Motion-Twin\\Haxe\\std\\haxe\\Serializer.hx"
						__temp_executeDef1 = false;
						//line 42 "C:\\Motion-Twin\\Haxe\\std\\haxe\\Serializer.hx"
						this.serialize(dynargs[0]);
					}
					
					//line 42 "C:\\Motion-Twin\\Haxe\\std\\haxe\\Serializer.hx"
					break;
				}
				
				
				case 375065361:
				{
					//line 42 "C:\\Motion-Twin\\Haxe\\std\\haxe\\Serializer.hx"
					if (field.equals("serializeString")) 
					{
						//line 42 "C:\\Motion-Twin\\Haxe\\std\\haxe\\Serializer.hx"
						__temp_executeDef1 = false;
						//line 42 "C:\\Motion-Twin\\Haxe\\std\\haxe\\Serializer.hx"
						this.serializeString(haxe.lang.Runtime.toString(dynargs[0]));
					}
					
					//line 42 "C:\\Motion-Twin\\Haxe\\std\\haxe\\Serializer.hx"
					break;
				}
				
				
				case -7657031:
				{
					//line 42 "C:\\Motion-Twin\\Haxe\\std\\haxe\\Serializer.hx"
					if (field.equals("serializeFields")) 
					{
						//line 42 "C:\\Motion-Twin\\Haxe\\std\\haxe\\Serializer.hx"
						__temp_executeDef1 = false;
						//line 42 "C:\\Motion-Twin\\Haxe\\std\\haxe\\Serializer.hx"
						this.serializeFields(dynargs[0]);
					}
					
					//line 42 "C:\\Motion-Twin\\Haxe\\std\\haxe\\Serializer.hx"
					break;
				}
				
				
				case 861138323:
				{
					//line 42 "C:\\Motion-Twin\\Haxe\\std\\haxe\\Serializer.hx"
					if (field.equals("serializeRef")) 
					{
						//line 42 "C:\\Motion-Twin\\Haxe\\std\\haxe\\Serializer.hx"
						__temp_executeDef1 = false;
						//line 42 "C:\\Motion-Twin\\Haxe\\std\\haxe\\Serializer.hx"
						return this.serializeRef(dynargs[0]);
					}
					
					//line 42 "C:\\Motion-Twin\\Haxe\\std\\haxe\\Serializer.hx"
					break;
				}
				
				
			}
			
			//line 42 "C:\\Motion-Twin\\Haxe\\std\\haxe\\Serializer.hx"
			if (__temp_executeDef1) 
			{
				//line 42 "C:\\Motion-Twin\\Haxe\\std\\haxe\\Serializer.hx"
				return super.__hx_invokeField(field, dynargs);
			}
			
		}
		
		//line 42 "C:\\Motion-Twin\\Haxe\\std\\haxe\\Serializer.hx"
		return null;
	}
	
	
	@Override public void __hx_getFields(haxe.root.Array<java.lang.String> baseArr)
	{
		//line 42 "C:\\Motion-Twin\\Haxe\\std\\haxe\\Serializer.hx"
		baseArr.push("useEnumIndex");
		//line 42 "C:\\Motion-Twin\\Haxe\\std\\haxe\\Serializer.hx"
		baseArr.push("useCache");
		//line 42 "C:\\Motion-Twin\\Haxe\\std\\haxe\\Serializer.hx"
		baseArr.push("scount");
		//line 42 "C:\\Motion-Twin\\Haxe\\std\\haxe\\Serializer.hx"
		baseArr.push("shash");
		//line 42 "C:\\Motion-Twin\\Haxe\\std\\haxe\\Serializer.hx"
		baseArr.push("cache");
		//line 42 "C:\\Motion-Twin\\Haxe\\std\\haxe\\Serializer.hx"
		baseArr.push("buf");
		//line 42 "C:\\Motion-Twin\\Haxe\\std\\haxe\\Serializer.hx"
		super.__hx_getFields(baseArr);
	}
	
	
}


