// Generated by Haxe 4.0.0 (git build development @ be76e496e)
package haxe.root;

import haxe.root.*;

@SuppressWarnings(value={"rawtypes", "unchecked"})
public class Reflect extends haxe.lang.HxObject
{
	public Reflect(haxe.lang.EmptyObject empty)
	{
	}
	
	
	public Reflect()
	{
		//line 28 "C:\\Motion-Twin\\Haxe\\std\\java\\_std\\Reflect.hx"
		haxe.root.Reflect.__hx_ctor__Reflect(this);
	}
	
	
	protected static void __hx_ctor__Reflect(haxe.root.Reflect __hx_this)
	{
	}
	
	
	public static boolean hasField(java.lang.Object o, java.lang.String field)
	{
		//line 32 "C:\\Motion-Twin\\Haxe\\std\\java\\_std\\Reflect.hx"
		if (( o instanceof haxe.lang.IHxObject )) 
		{
			//line 33 "C:\\Motion-Twin\\Haxe\\std\\java\\_std\\Reflect.hx"
			return ( ! (haxe.lang.Runtime.eq(((haxe.lang.IHxObject) (o) ).__hx_getField(field, false, true, false), haxe.lang.Runtime.undefined)) );
		}
		
		//line 35 "C:\\Motion-Twin\\Haxe\\std\\java\\_std\\Reflect.hx"
		return haxe.lang.Runtime.slowHasField(o, field);
	}
	
	
	public static java.lang.Object field(java.lang.Object o, java.lang.String field)
	{
		//line 41 "C:\\Motion-Twin\\Haxe\\std\\java\\_std\\Reflect.hx"
		if (( o instanceof haxe.lang.IHxObject )) 
		{
			//line 42 "C:\\Motion-Twin\\Haxe\\std\\java\\_std\\Reflect.hx"
			return ((haxe.lang.IHxObject) (o) ).__hx_getField(field, false, false, false);
		}
		
		//line 44 "C:\\Motion-Twin\\Haxe\\std\\java\\_std\\Reflect.hx"
		return haxe.lang.Runtime.slowGetField(o, field, false);
	}
	
	
	public static void setField(java.lang.Object o, java.lang.String field, java.lang.Object value)
	{
		//line 50 "C:\\Motion-Twin\\Haxe\\std\\java\\_std\\Reflect.hx"
		if (( o instanceof haxe.lang.IHxObject )) 
		{
			//line 51 "C:\\Motion-Twin\\Haxe\\std\\java\\_std\\Reflect.hx"
			((haxe.lang.IHxObject) (o) ).__hx_setField(field, value, false);
		}
		else
		{
			//line 53 "C:\\Motion-Twin\\Haxe\\std\\java\\_std\\Reflect.hx"
			haxe.lang.Runtime.slowSetField(o, field, value);
		}
		
	}
	
	
	public static java.lang.Object callMethod(java.lang.Object o, java.lang.Object func, haxe.root.Array args)
	{
		//line 81 "C:\\Motion-Twin\\Haxe\\std\\java\\_std\\Reflect.hx"
		java.lang.Object[] ret = new java.lang.Object[args.length];
		//line 81 "C:\\Motion-Twin\\Haxe\\std\\java\\_std\\Reflect.hx"
		{
			//line 81 "C:\\Motion-Twin\\Haxe\\std\\java\\_std\\Reflect.hx"
			int _g1 = 0;
			//line 81 "C:\\Motion-Twin\\Haxe\\std\\java\\_std\\Reflect.hx"
			int _g = args.length;
			//line 81 "C:\\Motion-Twin\\Haxe\\std\\java\\_std\\Reflect.hx"
			while (( _g1 < _g ))
			{
				//line 81 "C:\\Motion-Twin\\Haxe\\std\\java\\_std\\Reflect.hx"
				int i = _g1++;
				//line 81 "C:\\Motion-Twin\\Haxe\\std\\java\\_std\\Reflect.hx"
				ret[i] = args.__get(i);
			}
			
		}
		
		//line 81 "C:\\Motion-Twin\\Haxe\\std\\java\\_std\\Reflect.hx"
		java.lang.Object[] args1 = ret;
		//line 82 "C:\\Motion-Twin\\Haxe\\std\\java\\_std\\Reflect.hx"
		return ((haxe.lang.Function) (func) ).__hx_invokeDynamic(args1);
	}
	
	
	public static haxe.root.Array<java.lang.String> fields(java.lang.Object o)
	{
		//line 88 "C:\\Motion-Twin\\Haxe\\std\\java\\_std\\Reflect.hx"
		if (( o instanceof haxe.lang.IHxObject )) 
		{
			//line 89 "C:\\Motion-Twin\\Haxe\\std\\java\\_std\\Reflect.hx"
			haxe.root.Array<java.lang.String> ret = new haxe.root.Array<java.lang.String>(new java.lang.String[]{});
			//line 90 "C:\\Motion-Twin\\Haxe\\std\\java\\_std\\Reflect.hx"
			((haxe.lang.IHxObject) (o) ).__hx_getFields(ret);
			//line 91 "C:\\Motion-Twin\\Haxe\\std\\java\\_std\\Reflect.hx"
			return ret;
		}
		else
		{
			//line 92 "C:\\Motion-Twin\\Haxe\\std\\java\\_std\\Reflect.hx"
			if (( o instanceof java.lang.Class )) 
			{
				//line 93 "C:\\Motion-Twin\\Haxe\\std\\java\\_std\\Reflect.hx"
				return haxe.root.Type.getClassFields(((java.lang.Class) (o) ));
			}
			else
			{
				//line 95 "C:\\Motion-Twin\\Haxe\\std\\java\\_std\\Reflect.hx"
				return new haxe.root.Array<java.lang.String>(new java.lang.String[]{});
			}
			
		}
		
	}
	
	
	public static boolean isFunction(java.lang.Object f)
	{
		//line 101 "C:\\Motion-Twin\\Haxe\\std\\java\\_std\\Reflect.hx"
		return ( f instanceof haxe.lang.Function );
	}
	
	
}


