// Generated by Haxe 4.0.0 (git build development @ be76e496e)
package haxe.lang;

import haxe.root.*;

@SuppressWarnings(value={"rawtypes", "unchecked"})
public interface IEquatable
{
	boolean equals(java.lang.Object to);
	
}


