// Generated by Haxe 4.0.0 (git build development @ be76e496e)
package backend;

import haxe.root.*;

@SuppressWarnings(value={"rawtypes", "unchecked"})
public class HaxeBackend extends cordova.backend.CustomServer
{
	public HaxeBackend(haxe.lang.EmptyObject empty)
	{
		//line 3 "E:\\work\\libhaxe\\hx-cordova-plugin\\demo\\hx-src\\backend\\HaxeBackend.hx"
		super(haxe.lang.EmptyObject.EMPTY);
	}
	
	
	public HaxeBackend()
	{
		//line 9 "E:\\work\\libhaxe\\hx-cordova-plugin\\src\\cordova\\backend\\CustomServer.hx"
		super(haxe.lang.EmptyObject.EMPTY);
		//line 9 "E:\\work\\libhaxe\\hx-cordova-plugin\\src\\cordova\\backend\\CustomServer.hx"
		backend.HaxeBackend.__hx_ctor_backend_HaxeBackend(this);
	}
	
	
	protected static void __hx_ctor_backend_HaxeBackend(backend.HaxeBackend __hx_this)
	{
		//line 9 "E:\\work\\libhaxe\\hx-cordova-plugin\\src\\cordova\\backend\\CustomServer.hx"
		cordova.backend.CustomServer.__hx_ctor_cordova_backend_CustomServer(__hx_this);
	}
	
	
	public java.lang.Object add(int a, int b)
	{
		//line 6 "E:\\work\\libhaxe\\hx-cordova-plugin\\demo\\hx-src\\backend\\HaxeBackend.hx"
		backend.HaxeBackend _gthis = this;
		//line 7 "E:\\work\\libhaxe\\hx-cordova-plugin\\demo\\hx-src\\backend\\HaxeBackend.hx"
		org.apache.cordova.CallbackContext ctx = this.popContext();
		//line 8 "E:\\work\\libhaxe\\hx-cordova-plugin\\demo\\hx-src\\backend\\HaxeBackend.hx"
		this.plugin.executeThreaded(new backend.HaxeBackend_add_8__Fun(ctx, b, a, _gthis));
		//line 11 "E:\\work\\libhaxe\\hx-cordova-plugin\\demo\\hx-src\\backend\\HaxeBackend.hx"
		return null;
	}
	
	
	@Override public java.lang.Object __hx_getField(java.lang.String field, boolean throwErrors, boolean isCheck, boolean handleProperties)
	{
		//line 3 "E:\\work\\libhaxe\\hx-cordova-plugin\\demo\\hx-src\\backend\\HaxeBackend.hx"
		{
			//line 3 "E:\\work\\libhaxe\\hx-cordova-plugin\\demo\\hx-src\\backend\\HaxeBackend.hx"
			boolean __temp_executeDef1 = true;
			//line 3 "E:\\work\\libhaxe\\hx-cordova-plugin\\demo\\hx-src\\backend\\HaxeBackend.hx"
			switch (field.hashCode())
			{
				case 96417:
				{
					//line 3 "E:\\work\\libhaxe\\hx-cordova-plugin\\demo\\hx-src\\backend\\HaxeBackend.hx"
					if (field.equals("add")) 
					{
						//line 3 "E:\\work\\libhaxe\\hx-cordova-plugin\\demo\\hx-src\\backend\\HaxeBackend.hx"
						__temp_executeDef1 = false;
						//line 3 "E:\\work\\libhaxe\\hx-cordova-plugin\\demo\\hx-src\\backend\\HaxeBackend.hx"
						return ((haxe.lang.Function) (new haxe.lang.Closure(this, "add")) );
					}
					
					//line 3 "E:\\work\\libhaxe\\hx-cordova-plugin\\demo\\hx-src\\backend\\HaxeBackend.hx"
					break;
				}
				
				
			}
			
			//line 3 "E:\\work\\libhaxe\\hx-cordova-plugin\\demo\\hx-src\\backend\\HaxeBackend.hx"
			if (__temp_executeDef1) 
			{
				//line 3 "E:\\work\\libhaxe\\hx-cordova-plugin\\demo\\hx-src\\backend\\HaxeBackend.hx"
				return super.__hx_getField(field, throwErrors, isCheck, handleProperties);
			}
			else
			{
				//line 3 "E:\\work\\libhaxe\\hx-cordova-plugin\\demo\\hx-src\\backend\\HaxeBackend.hx"
				throw null;
			}
			
		}
		
	}
	
	
	@Override public java.lang.Object __hx_invokeField(java.lang.String field, java.lang.Object[] dynargs)
	{
		//line 3 "E:\\work\\libhaxe\\hx-cordova-plugin\\demo\\hx-src\\backend\\HaxeBackend.hx"
		{
			//line 3 "E:\\work\\libhaxe\\hx-cordova-plugin\\demo\\hx-src\\backend\\HaxeBackend.hx"
			boolean __temp_executeDef1 = true;
			//line 3 "E:\\work\\libhaxe\\hx-cordova-plugin\\demo\\hx-src\\backend\\HaxeBackend.hx"
			switch (field.hashCode())
			{
				case 96417:
				{
					//line 3 "E:\\work\\libhaxe\\hx-cordova-plugin\\demo\\hx-src\\backend\\HaxeBackend.hx"
					if (field.equals("add")) 
					{
						//line 3 "E:\\work\\libhaxe\\hx-cordova-plugin\\demo\\hx-src\\backend\\HaxeBackend.hx"
						__temp_executeDef1 = false;
						//line 3 "E:\\work\\libhaxe\\hx-cordova-plugin\\demo\\hx-src\\backend\\HaxeBackend.hx"
						return this.add(((int) (haxe.lang.Runtime.toInt(dynargs[0])) ), ((int) (haxe.lang.Runtime.toInt(dynargs[1])) ));
					}
					
					//line 3 "E:\\work\\libhaxe\\hx-cordova-plugin\\demo\\hx-src\\backend\\HaxeBackend.hx"
					break;
				}
				
				
			}
			
			//line 3 "E:\\work\\libhaxe\\hx-cordova-plugin\\demo\\hx-src\\backend\\HaxeBackend.hx"
			if (__temp_executeDef1) 
			{
				//line 3 "E:\\work\\libhaxe\\hx-cordova-plugin\\demo\\hx-src\\backend\\HaxeBackend.hx"
				return super.__hx_invokeField(field, dynargs);
			}
			else
			{
				//line 3 "E:\\work\\libhaxe\\hx-cordova-plugin\\demo\\hx-src\\backend\\HaxeBackend.hx"
				throw null;
			}
			
		}
		
	}
	
	
}


