// Generated by Haxe 4.0.0 (git build development @ be76e496e)
package backend;

import haxe.root.*;

@SuppressWarnings(value={"rawtypes", "unchecked"})
public class HaxeBackend_add_8__Fun extends haxe.lang.Function
{
	public HaxeBackend_add_8__Fun(org.apache.cordova.CallbackContext ctx, int b, int a, backend.HaxeBackend _gthis)
	{
		//line 9 "E:\\work\\libhaxe\\hx-cordova-plugin\\demo\\hx-src\\backend\\HaxeBackend.hx"
		super(0, 0);
		//line 9 "E:\\work\\libhaxe\\hx-cordova-plugin\\demo\\hx-src\\backend\\HaxeBackend.hx"
		this.ctx = ctx;
		//line 9 "E:\\work\\libhaxe\\hx-cordova-plugin\\demo\\hx-src\\backend\\HaxeBackend.hx"
		this.b = b;
		//line 9 "E:\\work\\libhaxe\\hx-cordova-plugin\\demo\\hx-src\\backend\\HaxeBackend.hx"
		this.a = a;
		//line 9 "E:\\work\\libhaxe\\hx-cordova-plugin\\demo\\hx-src\\backend\\HaxeBackend.hx"
		this._gthis = _gthis;
	}
	
	
	@Override public java.lang.Object __hx_invoke0_o()
	{
		//line 9 "E:\\work\\libhaxe\\hx-cordova-plugin\\demo\\hx-src\\backend\\HaxeBackend.hx"
		this._gthis.success(( this.a + this.b ), this.ctx);
		//line 9 "E:\\work\\libhaxe\\hx-cordova-plugin\\demo\\hx-src\\backend\\HaxeBackend.hx"
		return null;
	}
	
	
	public org.apache.cordova.CallbackContext ctx;
	
	public int b;
	
	public int a;
	
	public backend.HaxeBackend _gthis;
	
}


