// Generated by Haxe 4.0.0 (git build development @ be76e496e)
package haxe.ds;

import haxe.root.*;

@SuppressWarnings(value={"rawtypes", "unchecked"})
public class ObjectMap<K, V> extends haxe.lang.HxObject implements haxe.IMap<K, V>
{
	public ObjectMap(haxe.lang.EmptyObject empty)
	{
	}
	
	
	public ObjectMap()
	{
		//line 61 "C:\\Motion-Twin\\Haxe\\std\\java\\_std\\haxe\\ds\\ObjectMap.hx"
		haxe.ds.ObjectMap.__hx_ctor_haxe_ds_ObjectMap(((haxe.ds.ObjectMap<K, V>) (this) ));
	}
	
	
	protected static <K_c, V_c> void __hx_ctor_haxe_ds_ObjectMap(haxe.ds.ObjectMap<K_c, V_c> __hx_this)
	{
		//line 64 "C:\\Motion-Twin\\Haxe\\std\\java\\_std\\haxe\\ds\\ObjectMap.hx"
		__hx_this.cachedIndex = -1;
	}
	
	
	public int[] hashes;
	
	public K[] _keys;
	
	public V[] vals;
	
	public int nBuckets;
	
	public int size;
	
	public int nOccupied;
	
	public int upperBound;
	
	public K cachedKey;
	
	public int cachedIndex;
	
	public void set(K key, V value)
	{
		//line 70 "C:\\Motion-Twin\\Haxe\\std\\java\\_std\\haxe\\ds\\ObjectMap.hx"
		int x = 0;
		//line 70 "C:\\Motion-Twin\\Haxe\\std\\java\\_std\\haxe\\ds\\ObjectMap.hx"
		int k = 0;
		//line 71 "C:\\Motion-Twin\\Haxe\\std\\java\\_std\\haxe\\ds\\ObjectMap.hx"
		if (( this.nOccupied >= this.upperBound )) 
		{
			//line 73 "C:\\Motion-Twin\\Haxe\\std\\java\\_std\\haxe\\ds\\ObjectMap.hx"
			if (( this.nBuckets > ( this.size << 1 ) )) 
			{
				//line 74 "C:\\Motion-Twin\\Haxe\\std\\java\\_std\\haxe\\ds\\ObjectMap.hx"
				this.resize(( this.nBuckets - 1 ));
			}
			else
			{
				//line 76 "C:\\Motion-Twin\\Haxe\\std\\java\\_std\\haxe\\ds\\ObjectMap.hx"
				this.resize(( this.nBuckets + 2 ));
			}
			
		}
		
		//line 79 "C:\\Motion-Twin\\Haxe\\std\\java\\_std\\haxe\\ds\\ObjectMap.hx"
		int[] hashes = this.hashes;
		//line 79 "C:\\Motion-Twin\\Haxe\\std\\java\\_std\\haxe\\ds\\ObjectMap.hx"
		K[] keys = this._keys;
		//line 79 "C:\\Motion-Twin\\Haxe\\std\\java\\_std\\haxe\\ds\\ObjectMap.hx"
		int[] hashes1 = hashes;
		//line 80 "C:\\Motion-Twin\\Haxe\\std\\java\\_std\\haxe\\ds\\ObjectMap.hx"
		{
			//line 81 "C:\\Motion-Twin\\Haxe\\std\\java\\_std\\haxe\\ds\\ObjectMap.hx"
			int mask = ( (( this.nBuckets == 0 )) ? (0) : (( this.nBuckets - 1 )) );
			//line 82 "C:\\Motion-Twin\\Haxe\\std\\java\\_std\\haxe\\ds\\ObjectMap.hx"
			x = this.nBuckets;
			//line 82 "C:\\Motion-Twin\\Haxe\\std\\java\\_std\\haxe\\ds\\ObjectMap.hx"
			int site = x;
			//line 83 "C:\\Motion-Twin\\Haxe\\std\\java\\_std\\haxe\\ds\\ObjectMap.hx"
			int k1 = ((java.lang.Object) (key) ).hashCode();
			//line 83 "C:\\Motion-Twin\\Haxe\\std\\java\\_std\\haxe\\ds\\ObjectMap.hx"
			k1 = ( ( k1 + 2127912214 ) + (( k1 << 12 )) );
			//line 83 "C:\\Motion-Twin\\Haxe\\std\\java\\_std\\haxe\\ds\\ObjectMap.hx"
			k1 = ( ( k1 ^ -949894596 ) ^ ( k1 >> 19 ) );
			//line 83 "C:\\Motion-Twin\\Haxe\\std\\java\\_std\\haxe\\ds\\ObjectMap.hx"
			k1 = ( ( k1 + 374761393 ) + (( k1 << 5 )) );
			//line 83 "C:\\Motion-Twin\\Haxe\\std\\java\\_std\\haxe\\ds\\ObjectMap.hx"
			k1 = ( ( k1 + -744332180 ) ^ ( k1 << 9 ) );
			//line 83 "C:\\Motion-Twin\\Haxe\\std\\java\\_std\\haxe\\ds\\ObjectMap.hx"
			k1 = ( ( k1 + -42973499 ) + (( k1 << 3 )) );
			//line 83 "C:\\Motion-Twin\\Haxe\\std\\java\\_std\\haxe\\ds\\ObjectMap.hx"
			k1 = ( ( k1 ^ -1252372727 ) ^ ( k1 >> 16 ) );
			//line 83 "C:\\Motion-Twin\\Haxe\\std\\java\\_std\\haxe\\ds\\ObjectMap.hx"
			int ret = k1;
			//line 83 "C:\\Motion-Twin\\Haxe\\std\\java\\_std\\haxe\\ds\\ObjectMap.hx"
			if (( (( ret & -2 )) == 0 )) 
			{
				//line 83 "C:\\Motion-Twin\\Haxe\\std\\java\\_std\\haxe\\ds\\ObjectMap.hx"
				if (( ret == 0 )) 
				{
					//line 83 "C:\\Motion-Twin\\Haxe\\std\\java\\_std\\haxe\\ds\\ObjectMap.hx"
					ret = 2;
				}
				else
				{
					//line 83 "C:\\Motion-Twin\\Haxe\\std\\java\\_std\\haxe\\ds\\ObjectMap.hx"
					ret = -1;
				}
				
			}
			
			//line 83 "C:\\Motion-Twin\\Haxe\\std\\java\\_std\\haxe\\ds\\ObjectMap.hx"
			k = ret;
			//line 84 "C:\\Motion-Twin\\Haxe\\std\\java\\_std\\haxe\\ds\\ObjectMap.hx"
			int i = ( k & mask );
			//line 84 "C:\\Motion-Twin\\Haxe\\std\\java\\_std\\haxe\\ds\\ObjectMap.hx"
			int nProbes = 0;
			//line 86 "C:\\Motion-Twin\\Haxe\\std\\java\\_std\\haxe\\ds\\ObjectMap.hx"
			int delKey = -1;
			//line 88 "C:\\Motion-Twin\\Haxe\\std\\java\\_std\\haxe\\ds\\ObjectMap.hx"
			if (( hashes1[i] == 0 )) 
			{
				//line 89 "C:\\Motion-Twin\\Haxe\\std\\java\\_std\\haxe\\ds\\ObjectMap.hx"
				x = i;
			}
			else
			{
				//line 92 "C:\\Motion-Twin\\Haxe\\std\\java\\_std\\haxe\\ds\\ObjectMap.hx"
				int last = i;
				//line 92 "C:\\Motion-Twin\\Haxe\\std\\java\\_std\\haxe\\ds\\ObjectMap.hx"
				int flag = 0;
				//line 93 "C:\\Motion-Twin\\Haxe\\std\\java\\_std\\haxe\\ds\\ObjectMap.hx"
				while (true)
				{
					//line 93 "C:\\Motion-Twin\\Haxe\\std\\java\\_std\\haxe\\ds\\ObjectMap.hx"
					flag = hashes1[i];
					//line 93 "C:\\Motion-Twin\\Haxe\\std\\java\\_std\\haxe\\ds\\ObjectMap.hx"
					if ( ! (( ! ((( ( flag == 0 ) || ( ( flag == k ) && ((java.lang.Object) (keys[i]) ).equals(key) ) ))) )) ) 
					{
						//line 93 "C:\\Motion-Twin\\Haxe\\std\\java\\_std\\haxe\\ds\\ObjectMap.hx"
						break;
					}
					
					//line 95 "C:\\Motion-Twin\\Haxe\\std\\java\\_std\\haxe\\ds\\ObjectMap.hx"
					if (( ( flag == 1 ) && ( delKey == -1 ) )) 
					{
						//line 96 "C:\\Motion-Twin\\Haxe\\std\\java\\_std\\haxe\\ds\\ObjectMap.hx"
						delKey = i;
					}
					
					//line 97 "C:\\Motion-Twin\\Haxe\\std\\java\\_std\\haxe\\ds\\ObjectMap.hx"
					i = ( ( i +  ++ nProbes ) & mask );
				}
				
				//line 105 "C:\\Motion-Twin\\Haxe\\std\\java\\_std\\haxe\\ds\\ObjectMap.hx"
				if (( ( flag == 0 ) && ( delKey != -1 ) )) 
				{
					//line 106 "C:\\Motion-Twin\\Haxe\\std\\java\\_std\\haxe\\ds\\ObjectMap.hx"
					x = delKey;
				}
				else
				{
					//line 108 "C:\\Motion-Twin\\Haxe\\std\\java\\_std\\haxe\\ds\\ObjectMap.hx"
					x = i;
				}
				
			}
			
		}
		
		//line 118 "C:\\Motion-Twin\\Haxe\\std\\java\\_std\\haxe\\ds\\ObjectMap.hx"
		int flag1 = hashes1[x];
		//line 119 "C:\\Motion-Twin\\Haxe\\std\\java\\_std\\haxe\\ds\\ObjectMap.hx"
		if (( flag1 == 0 )) 
		{
			//line 121 "C:\\Motion-Twin\\Haxe\\std\\java\\_std\\haxe\\ds\\ObjectMap.hx"
			keys[x] = key;
			//line 122 "C:\\Motion-Twin\\Haxe\\std\\java\\_std\\haxe\\ds\\ObjectMap.hx"
			this.vals[x] = value;
			//line 123 "C:\\Motion-Twin\\Haxe\\std\\java\\_std\\haxe\\ds\\ObjectMap.hx"
			hashes1[x] = k;
			//line 124 "C:\\Motion-Twin\\Haxe\\std\\java\\_std\\haxe\\ds\\ObjectMap.hx"
			this.size++;
			//line 125 "C:\\Motion-Twin\\Haxe\\std\\java\\_std\\haxe\\ds\\ObjectMap.hx"
			this.nOccupied++;
		}
		else
		{
			//line 126 "C:\\Motion-Twin\\Haxe\\std\\java\\_std\\haxe\\ds\\ObjectMap.hx"
			if (( flag1 == 1 )) 
			{
				//line 127 "C:\\Motion-Twin\\Haxe\\std\\java\\_std\\haxe\\ds\\ObjectMap.hx"
				keys[x] = key;
				//line 128 "C:\\Motion-Twin\\Haxe\\std\\java\\_std\\haxe\\ds\\ObjectMap.hx"
				this.vals[x] = value;
				//line 129 "C:\\Motion-Twin\\Haxe\\std\\java\\_std\\haxe\\ds\\ObjectMap.hx"
				hashes1[x] = k;
				//line 130 "C:\\Motion-Twin\\Haxe\\std\\java\\_std\\haxe\\ds\\ObjectMap.hx"
				this.size++;
			}
			else
			{
				//line 133 "C:\\Motion-Twin\\Haxe\\std\\java\\_std\\haxe\\ds\\ObjectMap.hx"
				this.vals[x] = value;
			}
			
		}
		
		//line 137 "C:\\Motion-Twin\\Haxe\\std\\java\\_std\\haxe\\ds\\ObjectMap.hx"
		this.cachedIndex = x;
		//line 138 "C:\\Motion-Twin\\Haxe\\std\\java\\_std\\haxe\\ds\\ObjectMap.hx"
		this.cachedKey = key;
	}
	
	
	public int lookup(K key)
	{
		//line 144 "C:\\Motion-Twin\\Haxe\\std\\java\\_std\\haxe\\ds\\ObjectMap.hx"
		if (( this.nBuckets != 0 )) 
		{
			//line 146 "C:\\Motion-Twin\\Haxe\\std\\java\\_std\\haxe\\ds\\ObjectMap.hx"
			int[] hashes = this.hashes;
			//line 146 "C:\\Motion-Twin\\Haxe\\std\\java\\_std\\haxe\\ds\\ObjectMap.hx"
			K[] keys = this._keys;
			//line 148 "C:\\Motion-Twin\\Haxe\\std\\java\\_std\\haxe\\ds\\ObjectMap.hx"
			int mask = ( this.nBuckets - 1 );
			//line 148 "C:\\Motion-Twin\\Haxe\\std\\java\\_std\\haxe\\ds\\ObjectMap.hx"
			int k = ((java.lang.Object) (key) ).hashCode();
			//line 148 "C:\\Motion-Twin\\Haxe\\std\\java\\_std\\haxe\\ds\\ObjectMap.hx"
			k = ( ( k + 2127912214 ) + (( k << 12 )) );
			//line 148 "C:\\Motion-Twin\\Haxe\\std\\java\\_std\\haxe\\ds\\ObjectMap.hx"
			k = ( ( k ^ -949894596 ) ^ ( k >> 19 ) );
			//line 148 "C:\\Motion-Twin\\Haxe\\std\\java\\_std\\haxe\\ds\\ObjectMap.hx"
			k = ( ( k + 374761393 ) + (( k << 5 )) );
			//line 148 "C:\\Motion-Twin\\Haxe\\std\\java\\_std\\haxe\\ds\\ObjectMap.hx"
			k = ( ( k + -744332180 ) ^ ( k << 9 ) );
			//line 148 "C:\\Motion-Twin\\Haxe\\std\\java\\_std\\haxe\\ds\\ObjectMap.hx"
			k = ( ( k + -42973499 ) + (( k << 3 )) );
			//line 148 "C:\\Motion-Twin\\Haxe\\std\\java\\_std\\haxe\\ds\\ObjectMap.hx"
			k = ( ( k ^ -1252372727 ) ^ ( k >> 16 ) );
			//line 148 "C:\\Motion-Twin\\Haxe\\std\\java\\_std\\haxe\\ds\\ObjectMap.hx"
			int ret = k;
			//line 148 "C:\\Motion-Twin\\Haxe\\std\\java\\_std\\haxe\\ds\\ObjectMap.hx"
			if (( (( ret & -2 )) == 0 )) 
			{
				//line 148 "C:\\Motion-Twin\\Haxe\\std\\java\\_std\\haxe\\ds\\ObjectMap.hx"
				if (( ret == 0 )) 
				{
					//line 148 "C:\\Motion-Twin\\Haxe\\std\\java\\_std\\haxe\\ds\\ObjectMap.hx"
					ret = 2;
				}
				else
				{
					//line 148 "C:\\Motion-Twin\\Haxe\\std\\java\\_std\\haxe\\ds\\ObjectMap.hx"
					ret = -1;
				}
				
			}
			
			//line 148 "C:\\Motion-Twin\\Haxe\\std\\java\\_std\\haxe\\ds\\ObjectMap.hx"
			int hash = ret;
			//line 148 "C:\\Motion-Twin\\Haxe\\std\\java\\_std\\haxe\\ds\\ObjectMap.hx"
			int k1 = hash;
			//line 148 "C:\\Motion-Twin\\Haxe\\std\\java\\_std\\haxe\\ds\\ObjectMap.hx"
			int nProbes = 0;
			//line 149 "C:\\Motion-Twin\\Haxe\\std\\java\\_std\\haxe\\ds\\ObjectMap.hx"
			int i = ( k1 & mask );
			//line 150 "C:\\Motion-Twin\\Haxe\\std\\java\\_std\\haxe\\ds\\ObjectMap.hx"
			int last = i;
			//line 150 "C:\\Motion-Twin\\Haxe\\std\\java\\_std\\haxe\\ds\\ObjectMap.hx"
			int flag = 0;
			//line 152 "C:\\Motion-Twin\\Haxe\\std\\java\\_std\\haxe\\ds\\ObjectMap.hx"
			while (true)
			{
				//line 152 "C:\\Motion-Twin\\Haxe\\std\\java\\_std\\haxe\\ds\\ObjectMap.hx"
				flag = hashes[i];
				//line 152 "C:\\Motion-Twin\\Haxe\\std\\java\\_std\\haxe\\ds\\ObjectMap.hx"
				if ( ! ((( ( flag != 0 ) && (( ( ( flag == 1 ) || ( flag != k1 ) ) ||  ! (((java.lang.Object) (keys[i]) ).equals(key))  )) ))) ) 
				{
					//line 152 "C:\\Motion-Twin\\Haxe\\std\\java\\_std\\haxe\\ds\\ObjectMap.hx"
					break;
				}
				
				//line 154 "C:\\Motion-Twin\\Haxe\\std\\java\\_std\\haxe\\ds\\ObjectMap.hx"
				i = ( ( i +  ++ nProbes ) & mask );
			}
			
			//line 167 "C:\\Motion-Twin\\Haxe\\std\\java\\_std\\haxe\\ds\\ObjectMap.hx"
			if (( (( flag & -2 )) == 0 )) 
			{
				//line 167 "C:\\Motion-Twin\\Haxe\\std\\java\\_std\\haxe\\ds\\ObjectMap.hx"
				return -1;
			}
			else
			{
				//line 167 "C:\\Motion-Twin\\Haxe\\std\\java\\_std\\haxe\\ds\\ObjectMap.hx"
				return i;
			}
			
		}
		
		//line 170 "C:\\Motion-Twin\\Haxe\\std\\java\\_std\\haxe\\ds\\ObjectMap.hx"
		return -1;
	}
	
	
	public void resize(int newNBuckets)
	{
		//line 176 "C:\\Motion-Twin\\Haxe\\std\\java\\_std\\haxe\\ds\\ObjectMap.hx"
		int[] newHash = null;
		//line 177 "C:\\Motion-Twin\\Haxe\\std\\java\\_std\\haxe\\ds\\ObjectMap.hx"
		int j = 1;
		//line 178 "C:\\Motion-Twin\\Haxe\\std\\java\\_std\\haxe\\ds\\ObjectMap.hx"
		{
			//line 179 "C:\\Motion-Twin\\Haxe\\std\\java\\_std\\haxe\\ds\\ObjectMap.hx"
			int x = newNBuckets;
			//line 179 "C:\\Motion-Twin\\Haxe\\std\\java\\_std\\haxe\\ds\\ObjectMap.hx"
			 -- x;
			//line 179 "C:\\Motion-Twin\\Haxe\\std\\java\\_std\\haxe\\ds\\ObjectMap.hx"
			x |= ( x >>> 1 );
			//line 179 "C:\\Motion-Twin\\Haxe\\std\\java\\_std\\haxe\\ds\\ObjectMap.hx"
			x |= ( x >>> 2 );
			//line 179 "C:\\Motion-Twin\\Haxe\\std\\java\\_std\\haxe\\ds\\ObjectMap.hx"
			x |= ( x >>> 4 );
			//line 179 "C:\\Motion-Twin\\Haxe\\std\\java\\_std\\haxe\\ds\\ObjectMap.hx"
			x |= ( x >>> 8 );
			//line 179 "C:\\Motion-Twin\\Haxe\\std\\java\\_std\\haxe\\ds\\ObjectMap.hx"
			x |= ( x >>> 16 );
			//line 179 "C:\\Motion-Twin\\Haxe\\std\\java\\_std\\haxe\\ds\\ObjectMap.hx"
			newNBuckets =  ++ x;
			//line 180 "C:\\Motion-Twin\\Haxe\\std\\java\\_std\\haxe\\ds\\ObjectMap.hx"
			if (( newNBuckets < 4 )) 
			{
				//line 180 "C:\\Motion-Twin\\Haxe\\std\\java\\_std\\haxe\\ds\\ObjectMap.hx"
				newNBuckets = 4;
			}
			
			//line 181 "C:\\Motion-Twin\\Haxe\\std\\java\\_std\\haxe\\ds\\ObjectMap.hx"
			if (( this.size >= ( ( newNBuckets * 0.77 ) + 0.5 ) )) 
			{
				//line 183 "C:\\Motion-Twin\\Haxe\\std\\java\\_std\\haxe\\ds\\ObjectMap.hx"
				j = 0;
			}
			else
			{
				//line 185 "C:\\Motion-Twin\\Haxe\\std\\java\\_std\\haxe\\ds\\ObjectMap.hx"
				int nfSize = newNBuckets;
				//line 186 "C:\\Motion-Twin\\Haxe\\std\\java\\_std\\haxe\\ds\\ObjectMap.hx"
				newHash = new int[nfSize];
				//line 187 "C:\\Motion-Twin\\Haxe\\std\\java\\_std\\haxe\\ds\\ObjectMap.hx"
				if (( this.nBuckets < newNBuckets )) 
				{
					//line 189 "C:\\Motion-Twin\\Haxe\\std\\java\\_std\\haxe\\ds\\ObjectMap.hx"
					K[] k = ((K[]) (((java.lang.Object) (new java.lang.Object[newNBuckets]) )) );
					//line 190 "C:\\Motion-Twin\\Haxe\\std\\java\\_std\\haxe\\ds\\ObjectMap.hx"
					if (( this._keys != null )) 
					{
						//line 191 "C:\\Motion-Twin\\Haxe\\std\\java\\_std\\haxe\\ds\\ObjectMap.hx"
						java.lang.System.arraycopy(((java.lang.Object) (this._keys) ), ((int) (0) ), ((java.lang.Object) (k) ), ((int) (0) ), ((int) (this.nBuckets) ));
					}
					
					//line 192 "C:\\Motion-Twin\\Haxe\\std\\java\\_std\\haxe\\ds\\ObjectMap.hx"
					this._keys = k;
					//line 194 "C:\\Motion-Twin\\Haxe\\std\\java\\_std\\haxe\\ds\\ObjectMap.hx"
					V[] v = ((V[]) (((java.lang.Object) (new java.lang.Object[newNBuckets]) )) );
					//line 195 "C:\\Motion-Twin\\Haxe\\std\\java\\_std\\haxe\\ds\\ObjectMap.hx"
					if (( this.vals != null )) 
					{
						//line 196 "C:\\Motion-Twin\\Haxe\\std\\java\\_std\\haxe\\ds\\ObjectMap.hx"
						java.lang.System.arraycopy(((java.lang.Object) (this.vals) ), ((int) (0) ), ((java.lang.Object) (v) ), ((int) (0) ), ((int) (this.nBuckets) ));
					}
					
					//line 197 "C:\\Motion-Twin\\Haxe\\std\\java\\_std\\haxe\\ds\\ObjectMap.hx"
					this.vals = v;
				}
				
			}
			
		}
		
		//line 202 "C:\\Motion-Twin\\Haxe\\std\\java\\_std\\haxe\\ds\\ObjectMap.hx"
		if (( j != 0 )) 
		{
			//line 206 "C:\\Motion-Twin\\Haxe\\std\\java\\_std\\haxe\\ds\\ObjectMap.hx"
			this.cachedKey = null;
			//line 207 "C:\\Motion-Twin\\Haxe\\std\\java\\_std\\haxe\\ds\\ObjectMap.hx"
			this.cachedIndex = -1;
			//line 210 "C:\\Motion-Twin\\Haxe\\std\\java\\_std\\haxe\\ds\\ObjectMap.hx"
			j = -1;
			//line 211 "C:\\Motion-Twin\\Haxe\\std\\java\\_std\\haxe\\ds\\ObjectMap.hx"
			int nBuckets = this.nBuckets;
			//line 211 "C:\\Motion-Twin\\Haxe\\std\\java\\_std\\haxe\\ds\\ObjectMap.hx"
			K[] _keys = this._keys;
			//line 211 "C:\\Motion-Twin\\Haxe\\std\\java\\_std\\haxe\\ds\\ObjectMap.hx"
			V[] vals = this.vals;
			//line 211 "C:\\Motion-Twin\\Haxe\\std\\java\\_std\\haxe\\ds\\ObjectMap.hx"
			int[] hashes = this.hashes;
			//line 213 "C:\\Motion-Twin\\Haxe\\std\\java\\_std\\haxe\\ds\\ObjectMap.hx"
			int newMask = ( newNBuckets - 1 );
			//line 214 "C:\\Motion-Twin\\Haxe\\std\\java\\_std\\haxe\\ds\\ObjectMap.hx"
			while ((  ++ j < nBuckets ))
			{
				//line 216 "C:\\Motion-Twin\\Haxe\\std\\java\\_std\\haxe\\ds\\ObjectMap.hx"
				int k1 = hashes[j];
				//line 217 "C:\\Motion-Twin\\Haxe\\std\\java\\_std\\haxe\\ds\\ObjectMap.hx"
				if (( (( k1 & -2 )) != 0 )) 
				{
					//line 219 "C:\\Motion-Twin\\Haxe\\std\\java\\_std\\haxe\\ds\\ObjectMap.hx"
					K key = _keys[j];
					//line 220 "C:\\Motion-Twin\\Haxe\\std\\java\\_std\\haxe\\ds\\ObjectMap.hx"
					V val = vals[j];
					//line 222 "C:\\Motion-Twin\\Haxe\\std\\java\\_std\\haxe\\ds\\ObjectMap.hx"
					_keys[j] = null;
					//line 223 "C:\\Motion-Twin\\Haxe\\std\\java\\_std\\haxe\\ds\\ObjectMap.hx"
					vals[j] = null;
					//line 224 "C:\\Motion-Twin\\Haxe\\std\\java\\_std\\haxe\\ds\\ObjectMap.hx"
					hashes[j] = 1;
					//line 225 "C:\\Motion-Twin\\Haxe\\std\\java\\_std\\haxe\\ds\\ObjectMap.hx"
					while (true)
					{
						//line 227 "C:\\Motion-Twin\\Haxe\\std\\java\\_std\\haxe\\ds\\ObjectMap.hx"
						int nProbes = 0;
						//line 229 "C:\\Motion-Twin\\Haxe\\std\\java\\_std\\haxe\\ds\\ObjectMap.hx"
						int i = ( k1 & newMask );
						//line 231 "C:\\Motion-Twin\\Haxe\\std\\java\\_std\\haxe\\ds\\ObjectMap.hx"
						while (( newHash[i] != 0 ))
						{
							//line 232 "C:\\Motion-Twin\\Haxe\\std\\java\\_std\\haxe\\ds\\ObjectMap.hx"
							i = ( ( i +  ++ nProbes ) & newMask );
						}
						
						//line 234 "C:\\Motion-Twin\\Haxe\\std\\java\\_std\\haxe\\ds\\ObjectMap.hx"
						newHash[i] = k1;
						//line 236 "C:\\Motion-Twin\\Haxe\\std\\java\\_std\\haxe\\ds\\ObjectMap.hx"
						boolean tmp = false;
						//line 236 "C:\\Motion-Twin\\Haxe\\std\\java\\_std\\haxe\\ds\\ObjectMap.hx"
						if (( i < nBuckets )) 
						{
							//line 236 "C:\\Motion-Twin\\Haxe\\std\\java\\_std\\haxe\\ds\\ObjectMap.hx"
							k1 = hashes[i];
							//line 236 "C:\\Motion-Twin\\Haxe\\std\\java\\_std\\haxe\\ds\\ObjectMap.hx"
							tmp = ( (( k1 & -2 )) != 0 );
						}
						else
						{
							//line 236 "C:\\Motion-Twin\\Haxe\\std\\java\\_std\\haxe\\ds\\ObjectMap.hx"
							tmp = false;
						}
						
						//line 236 "C:\\Motion-Twin\\Haxe\\std\\java\\_std\\haxe\\ds\\ObjectMap.hx"
						if (tmp) 
						{
							//line 238 "C:\\Motion-Twin\\Haxe\\std\\java\\_std\\haxe\\ds\\ObjectMap.hx"
							{
								//line 239 "C:\\Motion-Twin\\Haxe\\std\\java\\_std\\haxe\\ds\\ObjectMap.hx"
								K tmp1 = _keys[i];
								//line 240 "C:\\Motion-Twin\\Haxe\\std\\java\\_std\\haxe\\ds\\ObjectMap.hx"
								_keys[i] = key;
								//line 241 "C:\\Motion-Twin\\Haxe\\std\\java\\_std\\haxe\\ds\\ObjectMap.hx"
								key = tmp1;
							}
							
							//line 243 "C:\\Motion-Twin\\Haxe\\std\\java\\_std\\haxe\\ds\\ObjectMap.hx"
							{
								//line 244 "C:\\Motion-Twin\\Haxe\\std\\java\\_std\\haxe\\ds\\ObjectMap.hx"
								V tmp2 = vals[i];
								//line 245 "C:\\Motion-Twin\\Haxe\\std\\java\\_std\\haxe\\ds\\ObjectMap.hx"
								vals[i] = val;
								//line 246 "C:\\Motion-Twin\\Haxe\\std\\java\\_std\\haxe\\ds\\ObjectMap.hx"
								val = tmp2;
							}
							
							//line 249 "C:\\Motion-Twin\\Haxe\\std\\java\\_std\\haxe\\ds\\ObjectMap.hx"
							hashes[i] = 1;
						}
						else
						{
							//line 251 "C:\\Motion-Twin\\Haxe\\std\\java\\_std\\haxe\\ds\\ObjectMap.hx"
							_keys[i] = key;
							//line 252 "C:\\Motion-Twin\\Haxe\\std\\java\\_std\\haxe\\ds\\ObjectMap.hx"
							vals[i] = val;
							//line 253 "C:\\Motion-Twin\\Haxe\\std\\java\\_std\\haxe\\ds\\ObjectMap.hx"
							break;
						}
						
					}
					
				}
				
			}
			
			//line 259 "C:\\Motion-Twin\\Haxe\\std\\java\\_std\\haxe\\ds\\ObjectMap.hx"
			if (( nBuckets > newNBuckets )) 
			{
				//line 261 "C:\\Motion-Twin\\Haxe\\std\\java\\_std\\haxe\\ds\\ObjectMap.hx"
				{
					//line 262 "C:\\Motion-Twin\\Haxe\\std\\java\\_std\\haxe\\ds\\ObjectMap.hx"
					K[] k2 = ((K[]) (((java.lang.Object) (new java.lang.Object[newNBuckets]) )) );
					//line 263 "C:\\Motion-Twin\\Haxe\\std\\java\\_std\\haxe\\ds\\ObjectMap.hx"
					java.lang.System.arraycopy(((java.lang.Object) (_keys) ), ((int) (0) ), ((java.lang.Object) (k2) ), ((int) (0) ), ((int) (newNBuckets) ));
					//line 264 "C:\\Motion-Twin\\Haxe\\std\\java\\_std\\haxe\\ds\\ObjectMap.hx"
					this._keys = k2;
				}
				
				//line 266 "C:\\Motion-Twin\\Haxe\\std\\java\\_std\\haxe\\ds\\ObjectMap.hx"
				{
					//line 267 "C:\\Motion-Twin\\Haxe\\std\\java\\_std\\haxe\\ds\\ObjectMap.hx"
					V[] v1 = ((V[]) (((java.lang.Object) (new java.lang.Object[newNBuckets]) )) );
					//line 268 "C:\\Motion-Twin\\Haxe\\std\\java\\_std\\haxe\\ds\\ObjectMap.hx"
					java.lang.System.arraycopy(((java.lang.Object) (vals) ), ((int) (0) ), ((java.lang.Object) (v1) ), ((int) (0) ), ((int) (newNBuckets) ));
					//line 269 "C:\\Motion-Twin\\Haxe\\std\\java\\_std\\haxe\\ds\\ObjectMap.hx"
					this.vals = v1;
				}
				
			}
			
			//line 273 "C:\\Motion-Twin\\Haxe\\std\\java\\_std\\haxe\\ds\\ObjectMap.hx"
			this.hashes = newHash;
			//line 274 "C:\\Motion-Twin\\Haxe\\std\\java\\_std\\haxe\\ds\\ObjectMap.hx"
			this.nBuckets = newNBuckets;
			//line 275 "C:\\Motion-Twin\\Haxe\\std\\java\\_std\\haxe\\ds\\ObjectMap.hx"
			this.nOccupied = this.size;
			//line 276 "C:\\Motion-Twin\\Haxe\\std\\java\\_std\\haxe\\ds\\ObjectMap.hx"
			this.upperBound = ((int) (( ( newNBuckets * 0.77 ) + .5 )) );
		}
		
	}
	
	
	public java.lang.Object get(K key)
	{
		//line 282 "C:\\Motion-Twin\\Haxe\\std\\java\\_std\\haxe\\ds\\ObjectMap.hx"
		int idx = -1;
		//line 284 "C:\\Motion-Twin\\Haxe\\std\\java\\_std\\haxe\\ds\\ObjectMap.hx"
		boolean tmp = false;
		//line 284 "C:\\Motion-Twin\\Haxe\\std\\java\\_std\\haxe\\ds\\ObjectMap.hx"
		if (haxe.lang.Runtime.eq(this.cachedKey, key)) 
		{
			//line 284 "C:\\Motion-Twin\\Haxe\\std\\java\\_std\\haxe\\ds\\ObjectMap.hx"
			idx = this.cachedIndex;
			//line 284 "C:\\Motion-Twin\\Haxe\\std\\java\\_std\\haxe\\ds\\ObjectMap.hx"
			tmp = ( idx != -1 );
		}
		else
		{
			//line 284 "C:\\Motion-Twin\\Haxe\\std\\java\\_std\\haxe\\ds\\ObjectMap.hx"
			tmp = false;
		}
		
		//line 284 "C:\\Motion-Twin\\Haxe\\std\\java\\_std\\haxe\\ds\\ObjectMap.hx"
		if (tmp) 
		{
			//line 286 "C:\\Motion-Twin\\Haxe\\std\\java\\_std\\haxe\\ds\\ObjectMap.hx"
			return this.vals[idx];
		}
		
		//line 290 "C:\\Motion-Twin\\Haxe\\std\\java\\_std\\haxe\\ds\\ObjectMap.hx"
		idx = this.lookup(key);
		//line 291 "C:\\Motion-Twin\\Haxe\\std\\java\\_std\\haxe\\ds\\ObjectMap.hx"
		if (( idx != -1 )) 
		{
			//line 294 "C:\\Motion-Twin\\Haxe\\std\\java\\_std\\haxe\\ds\\ObjectMap.hx"
			this.cachedKey = key;
			//line 295 "C:\\Motion-Twin\\Haxe\\std\\java\\_std\\haxe\\ds\\ObjectMap.hx"
			this.cachedIndex = idx;
			//line 298 "C:\\Motion-Twin\\Haxe\\std\\java\\_std\\haxe\\ds\\ObjectMap.hx"
			return this.vals[idx];
		}
		
		//line 301 "C:\\Motion-Twin\\Haxe\\std\\java\\_std\\haxe\\ds\\ObjectMap.hx"
		return null;
	}
	
	
	public java.lang.Object keys()
	{
		//line 386 "C:\\Motion-Twin\\Haxe\\std\\java\\_std\\haxe\\ds\\ObjectMap.hx"
		return new haxe.ds._ObjectMap.ObjectMapKeyIterator<K, V>(((haxe.ds.ObjectMap<K, V>) (this) ));
	}
	
	
	@Override public double __hx_setField_f(java.lang.String field, double value, boolean handleProperties)
	{
		//line 26 "C:\\Motion-Twin\\Haxe\\std\\java\\_std\\haxe\\ds\\ObjectMap.hx"
		{
			//line 26 "C:\\Motion-Twin\\Haxe\\std\\java\\_std\\haxe\\ds\\ObjectMap.hx"
			boolean __temp_executeDef1 = true;
			//line 26 "C:\\Motion-Twin\\Haxe\\std\\java\\_std\\haxe\\ds\\ObjectMap.hx"
			switch (field.hashCode())
			{
				case 1005083856:
				{
					//line 26 "C:\\Motion-Twin\\Haxe\\std\\java\\_std\\haxe\\ds\\ObjectMap.hx"
					if (field.equals("cachedIndex")) 
					{
						//line 26 "C:\\Motion-Twin\\Haxe\\std\\java\\_std\\haxe\\ds\\ObjectMap.hx"
						__temp_executeDef1 = false;
						//line 26 "C:\\Motion-Twin\\Haxe\\std\\java\\_std\\haxe\\ds\\ObjectMap.hx"
						this.cachedIndex = ((int) (value) );
						//line 26 "C:\\Motion-Twin\\Haxe\\std\\java\\_std\\haxe\\ds\\ObjectMap.hx"
						return value;
					}
					
					//line 26 "C:\\Motion-Twin\\Haxe\\std\\java\\_std\\haxe\\ds\\ObjectMap.hx"
					break;
				}
				
				
				case 325636987:
				{
					//line 26 "C:\\Motion-Twin\\Haxe\\std\\java\\_std\\haxe\\ds\\ObjectMap.hx"
					if (field.equals("nBuckets")) 
					{
						//line 26 "C:\\Motion-Twin\\Haxe\\std\\java\\_std\\haxe\\ds\\ObjectMap.hx"
						__temp_executeDef1 = false;
						//line 26 "C:\\Motion-Twin\\Haxe\\std\\java\\_std\\haxe\\ds\\ObjectMap.hx"
						this.nBuckets = ((int) (value) );
						//line 26 "C:\\Motion-Twin\\Haxe\\std\\java\\_std\\haxe\\ds\\ObjectMap.hx"
						return value;
					}
					
					//line 26 "C:\\Motion-Twin\\Haxe\\std\\java\\_std\\haxe\\ds\\ObjectMap.hx"
					break;
				}
				
				
				case -553141795:
				{
					//line 26 "C:\\Motion-Twin\\Haxe\\std\\java\\_std\\haxe\\ds\\ObjectMap.hx"
					if (field.equals("cachedKey")) 
					{
						//line 26 "C:\\Motion-Twin\\Haxe\\std\\java\\_std\\haxe\\ds\\ObjectMap.hx"
						__temp_executeDef1 = false;
						//line 26 "C:\\Motion-Twin\\Haxe\\std\\java\\_std\\haxe\\ds\\ObjectMap.hx"
						this.cachedKey = ((K) (((java.lang.Object) (value) )) );
						//line 26 "C:\\Motion-Twin\\Haxe\\std\\java\\_std\\haxe\\ds\\ObjectMap.hx"
						return ((double) (haxe.lang.Runtime.toDouble(((java.lang.Object) (value) ))) );
					}
					
					//line 26 "C:\\Motion-Twin\\Haxe\\std\\java\\_std\\haxe\\ds\\ObjectMap.hx"
					break;
				}
				
				
				case 3530753:
				{
					//line 26 "C:\\Motion-Twin\\Haxe\\std\\java\\_std\\haxe\\ds\\ObjectMap.hx"
					if (field.equals("size")) 
					{
						//line 26 "C:\\Motion-Twin\\Haxe\\std\\java\\_std\\haxe\\ds\\ObjectMap.hx"
						__temp_executeDef1 = false;
						//line 26 "C:\\Motion-Twin\\Haxe\\std\\java\\_std\\haxe\\ds\\ObjectMap.hx"
						this.size = ((int) (value) );
						//line 26 "C:\\Motion-Twin\\Haxe\\std\\java\\_std\\haxe\\ds\\ObjectMap.hx"
						return value;
					}
					
					//line 26 "C:\\Motion-Twin\\Haxe\\std\\java\\_std\\haxe\\ds\\ObjectMap.hx"
					break;
				}
				
				
				case -1690761732:
				{
					//line 26 "C:\\Motion-Twin\\Haxe\\std\\java\\_std\\haxe\\ds\\ObjectMap.hx"
					if (field.equals("upperBound")) 
					{
						//line 26 "C:\\Motion-Twin\\Haxe\\std\\java\\_std\\haxe\\ds\\ObjectMap.hx"
						__temp_executeDef1 = false;
						//line 26 "C:\\Motion-Twin\\Haxe\\std\\java\\_std\\haxe\\ds\\ObjectMap.hx"
						this.upperBound = ((int) (value) );
						//line 26 "C:\\Motion-Twin\\Haxe\\std\\java\\_std\\haxe\\ds\\ObjectMap.hx"
						return value;
					}
					
					//line 26 "C:\\Motion-Twin\\Haxe\\std\\java\\_std\\haxe\\ds\\ObjectMap.hx"
					break;
				}
				
				
				case -394102484:
				{
					//line 26 "C:\\Motion-Twin\\Haxe\\std\\java\\_std\\haxe\\ds\\ObjectMap.hx"
					if (field.equals("nOccupied")) 
					{
						//line 26 "C:\\Motion-Twin\\Haxe\\std\\java\\_std\\haxe\\ds\\ObjectMap.hx"
						__temp_executeDef1 = false;
						//line 26 "C:\\Motion-Twin\\Haxe\\std\\java\\_std\\haxe\\ds\\ObjectMap.hx"
						this.nOccupied = ((int) (value) );
						//line 26 "C:\\Motion-Twin\\Haxe\\std\\java\\_std\\haxe\\ds\\ObjectMap.hx"
						return value;
					}
					
					//line 26 "C:\\Motion-Twin\\Haxe\\std\\java\\_std\\haxe\\ds\\ObjectMap.hx"
					break;
				}
				
				
			}
			
			//line 26 "C:\\Motion-Twin\\Haxe\\std\\java\\_std\\haxe\\ds\\ObjectMap.hx"
			if (__temp_executeDef1) 
			{
				//line 26 "C:\\Motion-Twin\\Haxe\\std\\java\\_std\\haxe\\ds\\ObjectMap.hx"
				return super.__hx_setField_f(field, value, handleProperties);
			}
			else
			{
				//line 26 "C:\\Motion-Twin\\Haxe\\std\\java\\_std\\haxe\\ds\\ObjectMap.hx"
				throw null;
			}
			
		}
		
	}
	
	
	@Override public java.lang.Object __hx_setField(java.lang.String field, java.lang.Object value, boolean handleProperties)
	{
		//line 26 "C:\\Motion-Twin\\Haxe\\std\\java\\_std\\haxe\\ds\\ObjectMap.hx"
		{
			//line 26 "C:\\Motion-Twin\\Haxe\\std\\java\\_std\\haxe\\ds\\ObjectMap.hx"
			boolean __temp_executeDef1 = true;
			//line 26 "C:\\Motion-Twin\\Haxe\\std\\java\\_std\\haxe\\ds\\ObjectMap.hx"
			switch (field.hashCode())
			{
				case 1005083856:
				{
					//line 26 "C:\\Motion-Twin\\Haxe\\std\\java\\_std\\haxe\\ds\\ObjectMap.hx"
					if (field.equals("cachedIndex")) 
					{
						//line 26 "C:\\Motion-Twin\\Haxe\\std\\java\\_std\\haxe\\ds\\ObjectMap.hx"
						__temp_executeDef1 = false;
						//line 26 "C:\\Motion-Twin\\Haxe\\std\\java\\_std\\haxe\\ds\\ObjectMap.hx"
						this.cachedIndex = ((int) (haxe.lang.Runtime.toInt(value)) );
						//line 26 "C:\\Motion-Twin\\Haxe\\std\\java\\_std\\haxe\\ds\\ObjectMap.hx"
						return value;
					}
					
					//line 26 "C:\\Motion-Twin\\Haxe\\std\\java\\_std\\haxe\\ds\\ObjectMap.hx"
					break;
				}
				
				
				case -1224424900:
				{
					//line 26 "C:\\Motion-Twin\\Haxe\\std\\java\\_std\\haxe\\ds\\ObjectMap.hx"
					if (field.equals("hashes")) 
					{
						//line 26 "C:\\Motion-Twin\\Haxe\\std\\java\\_std\\haxe\\ds\\ObjectMap.hx"
						__temp_executeDef1 = false;
						//line 26 "C:\\Motion-Twin\\Haxe\\std\\java\\_std\\haxe\\ds\\ObjectMap.hx"
						this.hashes = ((int[]) (value) );
						//line 26 "C:\\Motion-Twin\\Haxe\\std\\java\\_std\\haxe\\ds\\ObjectMap.hx"
						return value;
					}
					
					//line 26 "C:\\Motion-Twin\\Haxe\\std\\java\\_std\\haxe\\ds\\ObjectMap.hx"
					break;
				}
				
				
				case -553141795:
				{
					//line 26 "C:\\Motion-Twin\\Haxe\\std\\java\\_std\\haxe\\ds\\ObjectMap.hx"
					if (field.equals("cachedKey")) 
					{
						//line 26 "C:\\Motion-Twin\\Haxe\\std\\java\\_std\\haxe\\ds\\ObjectMap.hx"
						__temp_executeDef1 = false;
						//line 26 "C:\\Motion-Twin\\Haxe\\std\\java\\_std\\haxe\\ds\\ObjectMap.hx"
						this.cachedKey = ((K) (value) );
						//line 26 "C:\\Motion-Twin\\Haxe\\std\\java\\_std\\haxe\\ds\\ObjectMap.hx"
						return value;
					}
					
					//line 26 "C:\\Motion-Twin\\Haxe\\std\\java\\_std\\haxe\\ds\\ObjectMap.hx"
					break;
				}
				
				
				case 91023059:
				{
					//line 26 "C:\\Motion-Twin\\Haxe\\std\\java\\_std\\haxe\\ds\\ObjectMap.hx"
					if (field.equals("_keys")) 
					{
						//line 26 "C:\\Motion-Twin\\Haxe\\std\\java\\_std\\haxe\\ds\\ObjectMap.hx"
						__temp_executeDef1 = false;
						//line 26 "C:\\Motion-Twin\\Haxe\\std\\java\\_std\\haxe\\ds\\ObjectMap.hx"
						this._keys = ((K[]) (value) );
						//line 26 "C:\\Motion-Twin\\Haxe\\std\\java\\_std\\haxe\\ds\\ObjectMap.hx"
						return value;
					}
					
					//line 26 "C:\\Motion-Twin\\Haxe\\std\\java\\_std\\haxe\\ds\\ObjectMap.hx"
					break;
				}
				
				
				case -1690761732:
				{
					//line 26 "C:\\Motion-Twin\\Haxe\\std\\java\\_std\\haxe\\ds\\ObjectMap.hx"
					if (field.equals("upperBound")) 
					{
						//line 26 "C:\\Motion-Twin\\Haxe\\std\\java\\_std\\haxe\\ds\\ObjectMap.hx"
						__temp_executeDef1 = false;
						//line 26 "C:\\Motion-Twin\\Haxe\\std\\java\\_std\\haxe\\ds\\ObjectMap.hx"
						this.upperBound = ((int) (haxe.lang.Runtime.toInt(value)) );
						//line 26 "C:\\Motion-Twin\\Haxe\\std\\java\\_std\\haxe\\ds\\ObjectMap.hx"
						return value;
					}
					
					//line 26 "C:\\Motion-Twin\\Haxe\\std\\java\\_std\\haxe\\ds\\ObjectMap.hx"
					break;
				}
				
				
				case 3612018:
				{
					//line 26 "C:\\Motion-Twin\\Haxe\\std\\java\\_std\\haxe\\ds\\ObjectMap.hx"
					if (field.equals("vals")) 
					{
						//line 26 "C:\\Motion-Twin\\Haxe\\std\\java\\_std\\haxe\\ds\\ObjectMap.hx"
						__temp_executeDef1 = false;
						//line 26 "C:\\Motion-Twin\\Haxe\\std\\java\\_std\\haxe\\ds\\ObjectMap.hx"
						this.vals = ((V[]) (value) );
						//line 26 "C:\\Motion-Twin\\Haxe\\std\\java\\_std\\haxe\\ds\\ObjectMap.hx"
						return value;
					}
					
					//line 26 "C:\\Motion-Twin\\Haxe\\std\\java\\_std\\haxe\\ds\\ObjectMap.hx"
					break;
				}
				
				
				case -394102484:
				{
					//line 26 "C:\\Motion-Twin\\Haxe\\std\\java\\_std\\haxe\\ds\\ObjectMap.hx"
					if (field.equals("nOccupied")) 
					{
						//line 26 "C:\\Motion-Twin\\Haxe\\std\\java\\_std\\haxe\\ds\\ObjectMap.hx"
						__temp_executeDef1 = false;
						//line 26 "C:\\Motion-Twin\\Haxe\\std\\java\\_std\\haxe\\ds\\ObjectMap.hx"
						this.nOccupied = ((int) (haxe.lang.Runtime.toInt(value)) );
						//line 26 "C:\\Motion-Twin\\Haxe\\std\\java\\_std\\haxe\\ds\\ObjectMap.hx"
						return value;
					}
					
					//line 26 "C:\\Motion-Twin\\Haxe\\std\\java\\_std\\haxe\\ds\\ObjectMap.hx"
					break;
				}
				
				
				case 325636987:
				{
					//line 26 "C:\\Motion-Twin\\Haxe\\std\\java\\_std\\haxe\\ds\\ObjectMap.hx"
					if (field.equals("nBuckets")) 
					{
						//line 26 "C:\\Motion-Twin\\Haxe\\std\\java\\_std\\haxe\\ds\\ObjectMap.hx"
						__temp_executeDef1 = false;
						//line 26 "C:\\Motion-Twin\\Haxe\\std\\java\\_std\\haxe\\ds\\ObjectMap.hx"
						this.nBuckets = ((int) (haxe.lang.Runtime.toInt(value)) );
						//line 26 "C:\\Motion-Twin\\Haxe\\std\\java\\_std\\haxe\\ds\\ObjectMap.hx"
						return value;
					}
					
					//line 26 "C:\\Motion-Twin\\Haxe\\std\\java\\_std\\haxe\\ds\\ObjectMap.hx"
					break;
				}
				
				
				case 3530753:
				{
					//line 26 "C:\\Motion-Twin\\Haxe\\std\\java\\_std\\haxe\\ds\\ObjectMap.hx"
					if (field.equals("size")) 
					{
						//line 26 "C:\\Motion-Twin\\Haxe\\std\\java\\_std\\haxe\\ds\\ObjectMap.hx"
						__temp_executeDef1 = false;
						//line 26 "C:\\Motion-Twin\\Haxe\\std\\java\\_std\\haxe\\ds\\ObjectMap.hx"
						this.size = ((int) (haxe.lang.Runtime.toInt(value)) );
						//line 26 "C:\\Motion-Twin\\Haxe\\std\\java\\_std\\haxe\\ds\\ObjectMap.hx"
						return value;
					}
					
					//line 26 "C:\\Motion-Twin\\Haxe\\std\\java\\_std\\haxe\\ds\\ObjectMap.hx"
					break;
				}
				
				
			}
			
			//line 26 "C:\\Motion-Twin\\Haxe\\std\\java\\_std\\haxe\\ds\\ObjectMap.hx"
			if (__temp_executeDef1) 
			{
				//line 26 "C:\\Motion-Twin\\Haxe\\std\\java\\_std\\haxe\\ds\\ObjectMap.hx"
				return super.__hx_setField(field, value, handleProperties);
			}
			else
			{
				//line 26 "C:\\Motion-Twin\\Haxe\\std\\java\\_std\\haxe\\ds\\ObjectMap.hx"
				throw null;
			}
			
		}
		
	}
	
	
	@Override public java.lang.Object __hx_getField(java.lang.String field, boolean throwErrors, boolean isCheck, boolean handleProperties)
	{
		//line 26 "C:\\Motion-Twin\\Haxe\\std\\java\\_std\\haxe\\ds\\ObjectMap.hx"
		{
			//line 26 "C:\\Motion-Twin\\Haxe\\std\\java\\_std\\haxe\\ds\\ObjectMap.hx"
			boolean __temp_executeDef1 = true;
			//line 26 "C:\\Motion-Twin\\Haxe\\std\\java\\_std\\haxe\\ds\\ObjectMap.hx"
			switch (field.hashCode())
			{
				case 3288564:
				{
					//line 26 "C:\\Motion-Twin\\Haxe\\std\\java\\_std\\haxe\\ds\\ObjectMap.hx"
					if (field.equals("keys")) 
					{
						//line 26 "C:\\Motion-Twin\\Haxe\\std\\java\\_std\\haxe\\ds\\ObjectMap.hx"
						__temp_executeDef1 = false;
						//line 26 "C:\\Motion-Twin\\Haxe\\std\\java\\_std\\haxe\\ds\\ObjectMap.hx"
						return ((haxe.lang.Function) (new haxe.lang.Closure(this, "keys")) );
					}
					
					//line 26 "C:\\Motion-Twin\\Haxe\\std\\java\\_std\\haxe\\ds\\ObjectMap.hx"
					break;
				}
				
				
				case -1224424900:
				{
					//line 26 "C:\\Motion-Twin\\Haxe\\std\\java\\_std\\haxe\\ds\\ObjectMap.hx"
					if (field.equals("hashes")) 
					{
						//line 26 "C:\\Motion-Twin\\Haxe\\std\\java\\_std\\haxe\\ds\\ObjectMap.hx"
						__temp_executeDef1 = false;
						//line 26 "C:\\Motion-Twin\\Haxe\\std\\java\\_std\\haxe\\ds\\ObjectMap.hx"
						return this.hashes;
					}
					
					//line 26 "C:\\Motion-Twin\\Haxe\\std\\java\\_std\\haxe\\ds\\ObjectMap.hx"
					break;
				}
				
				
				case 102230:
				{
					//line 26 "C:\\Motion-Twin\\Haxe\\std\\java\\_std\\haxe\\ds\\ObjectMap.hx"
					if (field.equals("get")) 
					{
						//line 26 "C:\\Motion-Twin\\Haxe\\std\\java\\_std\\haxe\\ds\\ObjectMap.hx"
						__temp_executeDef1 = false;
						//line 26 "C:\\Motion-Twin\\Haxe\\std\\java\\_std\\haxe\\ds\\ObjectMap.hx"
						return ((haxe.lang.Function) (new haxe.lang.Closure(this, "get")) );
					}
					
					//line 26 "C:\\Motion-Twin\\Haxe\\std\\java\\_std\\haxe\\ds\\ObjectMap.hx"
					break;
				}
				
				
				case 91023059:
				{
					//line 26 "C:\\Motion-Twin\\Haxe\\std\\java\\_std\\haxe\\ds\\ObjectMap.hx"
					if (field.equals("_keys")) 
					{
						//line 26 "C:\\Motion-Twin\\Haxe\\std\\java\\_std\\haxe\\ds\\ObjectMap.hx"
						__temp_executeDef1 = false;
						//line 26 "C:\\Motion-Twin\\Haxe\\std\\java\\_std\\haxe\\ds\\ObjectMap.hx"
						return this._keys;
					}
					
					//line 26 "C:\\Motion-Twin\\Haxe\\std\\java\\_std\\haxe\\ds\\ObjectMap.hx"
					break;
				}
				
				
				case -934437708:
				{
					//line 26 "C:\\Motion-Twin\\Haxe\\std\\java\\_std\\haxe\\ds\\ObjectMap.hx"
					if (field.equals("resize")) 
					{
						//line 26 "C:\\Motion-Twin\\Haxe\\std\\java\\_std\\haxe\\ds\\ObjectMap.hx"
						__temp_executeDef1 = false;
						//line 26 "C:\\Motion-Twin\\Haxe\\std\\java\\_std\\haxe\\ds\\ObjectMap.hx"
						return ((haxe.lang.Function) (new haxe.lang.Closure(this, "resize")) );
					}
					
					//line 26 "C:\\Motion-Twin\\Haxe\\std\\java\\_std\\haxe\\ds\\ObjectMap.hx"
					break;
				}
				
				
				case 3612018:
				{
					//line 26 "C:\\Motion-Twin\\Haxe\\std\\java\\_std\\haxe\\ds\\ObjectMap.hx"
					if (field.equals("vals")) 
					{
						//line 26 "C:\\Motion-Twin\\Haxe\\std\\java\\_std\\haxe\\ds\\ObjectMap.hx"
						__temp_executeDef1 = false;
						//line 26 "C:\\Motion-Twin\\Haxe\\std\\java\\_std\\haxe\\ds\\ObjectMap.hx"
						return this.vals;
					}
					
					//line 26 "C:\\Motion-Twin\\Haxe\\std\\java\\_std\\haxe\\ds\\ObjectMap.hx"
					break;
				}
				
				
				case -1097094790:
				{
					//line 26 "C:\\Motion-Twin\\Haxe\\std\\java\\_std\\haxe\\ds\\ObjectMap.hx"
					if (field.equals("lookup")) 
					{
						//line 26 "C:\\Motion-Twin\\Haxe\\std\\java\\_std\\haxe\\ds\\ObjectMap.hx"
						__temp_executeDef1 = false;
						//line 26 "C:\\Motion-Twin\\Haxe\\std\\java\\_std\\haxe\\ds\\ObjectMap.hx"
						return ((haxe.lang.Function) (new haxe.lang.Closure(this, "lookup")) );
					}
					
					//line 26 "C:\\Motion-Twin\\Haxe\\std\\java\\_std\\haxe\\ds\\ObjectMap.hx"
					break;
				}
				
				
				case 325636987:
				{
					//line 26 "C:\\Motion-Twin\\Haxe\\std\\java\\_std\\haxe\\ds\\ObjectMap.hx"
					if (field.equals("nBuckets")) 
					{
						//line 26 "C:\\Motion-Twin\\Haxe\\std\\java\\_std\\haxe\\ds\\ObjectMap.hx"
						__temp_executeDef1 = false;
						//line 26 "C:\\Motion-Twin\\Haxe\\std\\java\\_std\\haxe\\ds\\ObjectMap.hx"
						return this.nBuckets;
					}
					
					//line 26 "C:\\Motion-Twin\\Haxe\\std\\java\\_std\\haxe\\ds\\ObjectMap.hx"
					break;
				}
				
				
				case 113762:
				{
					//line 26 "C:\\Motion-Twin\\Haxe\\std\\java\\_std\\haxe\\ds\\ObjectMap.hx"
					if (field.equals("set")) 
					{
						//line 26 "C:\\Motion-Twin\\Haxe\\std\\java\\_std\\haxe\\ds\\ObjectMap.hx"
						__temp_executeDef1 = false;
						//line 26 "C:\\Motion-Twin\\Haxe\\std\\java\\_std\\haxe\\ds\\ObjectMap.hx"
						return ((haxe.lang.Function) (new haxe.lang.Closure(this, "set")) );
					}
					
					//line 26 "C:\\Motion-Twin\\Haxe\\std\\java\\_std\\haxe\\ds\\ObjectMap.hx"
					break;
				}
				
				
				case 3530753:
				{
					//line 26 "C:\\Motion-Twin\\Haxe\\std\\java\\_std\\haxe\\ds\\ObjectMap.hx"
					if (field.equals("size")) 
					{
						//line 26 "C:\\Motion-Twin\\Haxe\\std\\java\\_std\\haxe\\ds\\ObjectMap.hx"
						__temp_executeDef1 = false;
						//line 26 "C:\\Motion-Twin\\Haxe\\std\\java\\_std\\haxe\\ds\\ObjectMap.hx"
						return this.size;
					}
					
					//line 26 "C:\\Motion-Twin\\Haxe\\std\\java\\_std\\haxe\\ds\\ObjectMap.hx"
					break;
				}
				
				
				case 1005083856:
				{
					//line 26 "C:\\Motion-Twin\\Haxe\\std\\java\\_std\\haxe\\ds\\ObjectMap.hx"
					if (field.equals("cachedIndex")) 
					{
						//line 26 "C:\\Motion-Twin\\Haxe\\std\\java\\_std\\haxe\\ds\\ObjectMap.hx"
						__temp_executeDef1 = false;
						//line 26 "C:\\Motion-Twin\\Haxe\\std\\java\\_std\\haxe\\ds\\ObjectMap.hx"
						return this.cachedIndex;
					}
					
					//line 26 "C:\\Motion-Twin\\Haxe\\std\\java\\_std\\haxe\\ds\\ObjectMap.hx"
					break;
				}
				
				
				case -394102484:
				{
					//line 26 "C:\\Motion-Twin\\Haxe\\std\\java\\_std\\haxe\\ds\\ObjectMap.hx"
					if (field.equals("nOccupied")) 
					{
						//line 26 "C:\\Motion-Twin\\Haxe\\std\\java\\_std\\haxe\\ds\\ObjectMap.hx"
						__temp_executeDef1 = false;
						//line 26 "C:\\Motion-Twin\\Haxe\\std\\java\\_std\\haxe\\ds\\ObjectMap.hx"
						return this.nOccupied;
					}
					
					//line 26 "C:\\Motion-Twin\\Haxe\\std\\java\\_std\\haxe\\ds\\ObjectMap.hx"
					break;
				}
				
				
				case -553141795:
				{
					//line 26 "C:\\Motion-Twin\\Haxe\\std\\java\\_std\\haxe\\ds\\ObjectMap.hx"
					if (field.equals("cachedKey")) 
					{
						//line 26 "C:\\Motion-Twin\\Haxe\\std\\java\\_std\\haxe\\ds\\ObjectMap.hx"
						__temp_executeDef1 = false;
						//line 26 "C:\\Motion-Twin\\Haxe\\std\\java\\_std\\haxe\\ds\\ObjectMap.hx"
						return this.cachedKey;
					}
					
					//line 26 "C:\\Motion-Twin\\Haxe\\std\\java\\_std\\haxe\\ds\\ObjectMap.hx"
					break;
				}
				
				
				case -1690761732:
				{
					//line 26 "C:\\Motion-Twin\\Haxe\\std\\java\\_std\\haxe\\ds\\ObjectMap.hx"
					if (field.equals("upperBound")) 
					{
						//line 26 "C:\\Motion-Twin\\Haxe\\std\\java\\_std\\haxe\\ds\\ObjectMap.hx"
						__temp_executeDef1 = false;
						//line 26 "C:\\Motion-Twin\\Haxe\\std\\java\\_std\\haxe\\ds\\ObjectMap.hx"
						return this.upperBound;
					}
					
					//line 26 "C:\\Motion-Twin\\Haxe\\std\\java\\_std\\haxe\\ds\\ObjectMap.hx"
					break;
				}
				
				
			}
			
			//line 26 "C:\\Motion-Twin\\Haxe\\std\\java\\_std\\haxe\\ds\\ObjectMap.hx"
			if (__temp_executeDef1) 
			{
				//line 26 "C:\\Motion-Twin\\Haxe\\std\\java\\_std\\haxe\\ds\\ObjectMap.hx"
				return super.__hx_getField(field, throwErrors, isCheck, handleProperties);
			}
			else
			{
				//line 26 "C:\\Motion-Twin\\Haxe\\std\\java\\_std\\haxe\\ds\\ObjectMap.hx"
				throw null;
			}
			
		}
		
	}
	
	
	@Override public double __hx_getField_f(java.lang.String field, boolean throwErrors, boolean handleProperties)
	{
		//line 26 "C:\\Motion-Twin\\Haxe\\std\\java\\_std\\haxe\\ds\\ObjectMap.hx"
		{
			//line 26 "C:\\Motion-Twin\\Haxe\\std\\java\\_std\\haxe\\ds\\ObjectMap.hx"
			boolean __temp_executeDef1 = true;
			//line 26 "C:\\Motion-Twin\\Haxe\\std\\java\\_std\\haxe\\ds\\ObjectMap.hx"
			switch (field.hashCode())
			{
				case 1005083856:
				{
					//line 26 "C:\\Motion-Twin\\Haxe\\std\\java\\_std\\haxe\\ds\\ObjectMap.hx"
					if (field.equals("cachedIndex")) 
					{
						//line 26 "C:\\Motion-Twin\\Haxe\\std\\java\\_std\\haxe\\ds\\ObjectMap.hx"
						__temp_executeDef1 = false;
						//line 26 "C:\\Motion-Twin\\Haxe\\std\\java\\_std\\haxe\\ds\\ObjectMap.hx"
						return ((double) (this.cachedIndex) );
					}
					
					//line 26 "C:\\Motion-Twin\\Haxe\\std\\java\\_std\\haxe\\ds\\ObjectMap.hx"
					break;
				}
				
				
				case 325636987:
				{
					//line 26 "C:\\Motion-Twin\\Haxe\\std\\java\\_std\\haxe\\ds\\ObjectMap.hx"
					if (field.equals("nBuckets")) 
					{
						//line 26 "C:\\Motion-Twin\\Haxe\\std\\java\\_std\\haxe\\ds\\ObjectMap.hx"
						__temp_executeDef1 = false;
						//line 26 "C:\\Motion-Twin\\Haxe\\std\\java\\_std\\haxe\\ds\\ObjectMap.hx"
						return ((double) (this.nBuckets) );
					}
					
					//line 26 "C:\\Motion-Twin\\Haxe\\std\\java\\_std\\haxe\\ds\\ObjectMap.hx"
					break;
				}
				
				
				case -553141795:
				{
					//line 26 "C:\\Motion-Twin\\Haxe\\std\\java\\_std\\haxe\\ds\\ObjectMap.hx"
					if (field.equals("cachedKey")) 
					{
						//line 26 "C:\\Motion-Twin\\Haxe\\std\\java\\_std\\haxe\\ds\\ObjectMap.hx"
						__temp_executeDef1 = false;
						//line 26 "C:\\Motion-Twin\\Haxe\\std\\java\\_std\\haxe\\ds\\ObjectMap.hx"
						return ((double) (haxe.lang.Runtime.toDouble(((java.lang.Object) (this.cachedKey) ))) );
					}
					
					//line 26 "C:\\Motion-Twin\\Haxe\\std\\java\\_std\\haxe\\ds\\ObjectMap.hx"
					break;
				}
				
				
				case 3530753:
				{
					//line 26 "C:\\Motion-Twin\\Haxe\\std\\java\\_std\\haxe\\ds\\ObjectMap.hx"
					if (field.equals("size")) 
					{
						//line 26 "C:\\Motion-Twin\\Haxe\\std\\java\\_std\\haxe\\ds\\ObjectMap.hx"
						__temp_executeDef1 = false;
						//line 26 "C:\\Motion-Twin\\Haxe\\std\\java\\_std\\haxe\\ds\\ObjectMap.hx"
						return ((double) (this.size) );
					}
					
					//line 26 "C:\\Motion-Twin\\Haxe\\std\\java\\_std\\haxe\\ds\\ObjectMap.hx"
					break;
				}
				
				
				case -1690761732:
				{
					//line 26 "C:\\Motion-Twin\\Haxe\\std\\java\\_std\\haxe\\ds\\ObjectMap.hx"
					if (field.equals("upperBound")) 
					{
						//line 26 "C:\\Motion-Twin\\Haxe\\std\\java\\_std\\haxe\\ds\\ObjectMap.hx"
						__temp_executeDef1 = false;
						//line 26 "C:\\Motion-Twin\\Haxe\\std\\java\\_std\\haxe\\ds\\ObjectMap.hx"
						return ((double) (this.upperBound) );
					}
					
					//line 26 "C:\\Motion-Twin\\Haxe\\std\\java\\_std\\haxe\\ds\\ObjectMap.hx"
					break;
				}
				
				
				case -394102484:
				{
					//line 26 "C:\\Motion-Twin\\Haxe\\std\\java\\_std\\haxe\\ds\\ObjectMap.hx"
					if (field.equals("nOccupied")) 
					{
						//line 26 "C:\\Motion-Twin\\Haxe\\std\\java\\_std\\haxe\\ds\\ObjectMap.hx"
						__temp_executeDef1 = false;
						//line 26 "C:\\Motion-Twin\\Haxe\\std\\java\\_std\\haxe\\ds\\ObjectMap.hx"
						return ((double) (this.nOccupied) );
					}
					
					//line 26 "C:\\Motion-Twin\\Haxe\\std\\java\\_std\\haxe\\ds\\ObjectMap.hx"
					break;
				}
				
				
			}
			
			//line 26 "C:\\Motion-Twin\\Haxe\\std\\java\\_std\\haxe\\ds\\ObjectMap.hx"
			if (__temp_executeDef1) 
			{
				//line 26 "C:\\Motion-Twin\\Haxe\\std\\java\\_std\\haxe\\ds\\ObjectMap.hx"
				return super.__hx_getField_f(field, throwErrors, handleProperties);
			}
			else
			{
				//line 26 "C:\\Motion-Twin\\Haxe\\std\\java\\_std\\haxe\\ds\\ObjectMap.hx"
				throw null;
			}
			
		}
		
	}
	
	
	@Override public java.lang.Object __hx_invokeField(java.lang.String field, java.lang.Object[] dynargs)
	{
		//line 26 "C:\\Motion-Twin\\Haxe\\std\\java\\_std\\haxe\\ds\\ObjectMap.hx"
		{
			//line 26 "C:\\Motion-Twin\\Haxe\\std\\java\\_std\\haxe\\ds\\ObjectMap.hx"
			boolean __temp_executeDef1 = true;
			//line 26 "C:\\Motion-Twin\\Haxe\\std\\java\\_std\\haxe\\ds\\ObjectMap.hx"
			switch (field.hashCode())
			{
				case 3288564:
				{
					//line 26 "C:\\Motion-Twin\\Haxe\\std\\java\\_std\\haxe\\ds\\ObjectMap.hx"
					if (field.equals("keys")) 
					{
						//line 26 "C:\\Motion-Twin\\Haxe\\std\\java\\_std\\haxe\\ds\\ObjectMap.hx"
						__temp_executeDef1 = false;
						//line 26 "C:\\Motion-Twin\\Haxe\\std\\java\\_std\\haxe\\ds\\ObjectMap.hx"
						return this.keys();
					}
					
					//line 26 "C:\\Motion-Twin\\Haxe\\std\\java\\_std\\haxe\\ds\\ObjectMap.hx"
					break;
				}
				
				
				case 113762:
				{
					//line 26 "C:\\Motion-Twin\\Haxe\\std\\java\\_std\\haxe\\ds\\ObjectMap.hx"
					if (field.equals("set")) 
					{
						//line 26 "C:\\Motion-Twin\\Haxe\\std\\java\\_std\\haxe\\ds\\ObjectMap.hx"
						__temp_executeDef1 = false;
						//line 26 "C:\\Motion-Twin\\Haxe\\std\\java\\_std\\haxe\\ds\\ObjectMap.hx"
						this.set(((K) (dynargs[0]) ), ((V) (dynargs[1]) ));
					}
					
					//line 26 "C:\\Motion-Twin\\Haxe\\std\\java\\_std\\haxe\\ds\\ObjectMap.hx"
					break;
				}
				
				
				case 102230:
				{
					//line 26 "C:\\Motion-Twin\\Haxe\\std\\java\\_std\\haxe\\ds\\ObjectMap.hx"
					if (field.equals("get")) 
					{
						//line 26 "C:\\Motion-Twin\\Haxe\\std\\java\\_std\\haxe\\ds\\ObjectMap.hx"
						__temp_executeDef1 = false;
						//line 26 "C:\\Motion-Twin\\Haxe\\std\\java\\_std\\haxe\\ds\\ObjectMap.hx"
						return this.get(((K) (dynargs[0]) ));
					}
					
					//line 26 "C:\\Motion-Twin\\Haxe\\std\\java\\_std\\haxe\\ds\\ObjectMap.hx"
					break;
				}
				
				
				case -1097094790:
				{
					//line 26 "C:\\Motion-Twin\\Haxe\\std\\java\\_std\\haxe\\ds\\ObjectMap.hx"
					if (field.equals("lookup")) 
					{
						//line 26 "C:\\Motion-Twin\\Haxe\\std\\java\\_std\\haxe\\ds\\ObjectMap.hx"
						__temp_executeDef1 = false;
						//line 26 "C:\\Motion-Twin\\Haxe\\std\\java\\_std\\haxe\\ds\\ObjectMap.hx"
						return this.lookup(((K) (dynargs[0]) ));
					}
					
					//line 26 "C:\\Motion-Twin\\Haxe\\std\\java\\_std\\haxe\\ds\\ObjectMap.hx"
					break;
				}
				
				
				case -934437708:
				{
					//line 26 "C:\\Motion-Twin\\Haxe\\std\\java\\_std\\haxe\\ds\\ObjectMap.hx"
					if (field.equals("resize")) 
					{
						//line 26 "C:\\Motion-Twin\\Haxe\\std\\java\\_std\\haxe\\ds\\ObjectMap.hx"
						__temp_executeDef1 = false;
						//line 26 "C:\\Motion-Twin\\Haxe\\std\\java\\_std\\haxe\\ds\\ObjectMap.hx"
						this.resize(((int) (haxe.lang.Runtime.toInt(dynargs[0])) ));
					}
					
					//line 26 "C:\\Motion-Twin\\Haxe\\std\\java\\_std\\haxe\\ds\\ObjectMap.hx"
					break;
				}
				
				
			}
			
			//line 26 "C:\\Motion-Twin\\Haxe\\std\\java\\_std\\haxe\\ds\\ObjectMap.hx"
			if (__temp_executeDef1) 
			{
				//line 26 "C:\\Motion-Twin\\Haxe\\std\\java\\_std\\haxe\\ds\\ObjectMap.hx"
				return super.__hx_invokeField(field, dynargs);
			}
			
		}
		
		//line 26 "C:\\Motion-Twin\\Haxe\\std\\java\\_std\\haxe\\ds\\ObjectMap.hx"
		return null;
	}
	
	
	@Override public void __hx_getFields(haxe.root.Array<java.lang.String> baseArr)
	{
		//line 26 "C:\\Motion-Twin\\Haxe\\std\\java\\_std\\haxe\\ds\\ObjectMap.hx"
		baseArr.push("cachedIndex");
		//line 26 "C:\\Motion-Twin\\Haxe\\std\\java\\_std\\haxe\\ds\\ObjectMap.hx"
		baseArr.push("cachedKey");
		//line 26 "C:\\Motion-Twin\\Haxe\\std\\java\\_std\\haxe\\ds\\ObjectMap.hx"
		baseArr.push("upperBound");
		//line 26 "C:\\Motion-Twin\\Haxe\\std\\java\\_std\\haxe\\ds\\ObjectMap.hx"
		baseArr.push("nOccupied");
		//line 26 "C:\\Motion-Twin\\Haxe\\std\\java\\_std\\haxe\\ds\\ObjectMap.hx"
		baseArr.push("size");
		//line 26 "C:\\Motion-Twin\\Haxe\\std\\java\\_std\\haxe\\ds\\ObjectMap.hx"
		baseArr.push("nBuckets");
		//line 26 "C:\\Motion-Twin\\Haxe\\std\\java\\_std\\haxe\\ds\\ObjectMap.hx"
		baseArr.push("vals");
		//line 26 "C:\\Motion-Twin\\Haxe\\std\\java\\_std\\haxe\\ds\\ObjectMap.hx"
		baseArr.push("_keys");
		//line 26 "C:\\Motion-Twin\\Haxe\\std\\java\\_std\\haxe\\ds\\ObjectMap.hx"
		baseArr.push("hashes");
		//line 26 "C:\\Motion-Twin\\Haxe\\std\\java\\_std\\haxe\\ds\\ObjectMap.hx"
		super.__hx_getFields(baseArr);
	}
	
	
}


